In [3]:
import pandas as pd
import numpy as np
import json
import warnings

warnings.filterwarnings("ignore")

pd.set_option( "display.max_columns" , None)
pd.set_option( "display.max_rows", 200)
pd.set_option("display.max_colwidth" , None )

In [4]:
train_flag = pd.read_csv("../data/train_flag.csv")
test_flag = pd.read_csv("../data/test_flag.csv")

print( "Train Shape:", train_flag.shape )
print( "Test Shape:", test_flag.shape )

Train Shape: (261383, 3)
Test Shape: (46127, 2)

In [5]:
display(train_flag.head())
train_flag.info()

           uid NAME_CONTRACT_TYPE  TARGET
0  XDA69787158         Cash loans       0
1  BSE47789733         Cash loans       0
2  NTJ92213825         Cash loans       0
3  TCQ47571695         Cash loans       0
4  WJZ68772744         Cash loans       0

<class 'pandas.DataFrame'>
RangeIndex: 261383 entries, 0 to 261382
Data columns (total 3 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   uid                 261383 non-null  str
 1   NAME_CONTRACT_TYPE  261383 non-null  str
 2   TARGET              261383 non-null  int64
dtypes: int64(1), str(2)
memory usage: 11.3 MB

In [6]:
print(train_flag["TARGET"].value_counts() )

print(train_flag["TARGET"].value_counts(normalize=True)* 100)
# Imbalanced Dataset is present.

TARGET
0    240326
1     21057
Name: count, dtype: int64
TARGET
0    91.944006
1     8.055994
Name: proportion, dtype: float64

In [7]:
print( "Unique IDs:", train_flag["uid"].nunique() )
print ("Rows: ", len(train_flag) )

Unique IDs: 261383
Rows:  261383

In [8]:
missing = (train_flag.isnull().mean().sort_values(ascending=False)* 100 )

missing
# NO Missing Values in the dataset.

uid                   0.0
NAME_CONTRACT_TYPE    0.0
TARGET                0.0
dtype: float64

In [9]:
accounts = pd.read_json("../data/accounts_data_train.json")

print("Accounts Shape:", accounts.shape)
accounts.head()

Accounts Shape: (223918, 116)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115
0,"{'credit_type': 'Consumer credit', 'loan_amount': 272745.0, 'amount_overdue': 0.0, 'open_date': '2018-09-22', 'closed_date': '2020-02-22', 'payment_hist_string': '000000000000000000000010000000000000000000000000000', 'uid': 'AAA09044550'}","{'credit_type': 'Consumer credit', 'loan_amount': 4500.0, 'amount_overdue': 0.0, 'open_date': '2018-03-08', 'closed_date': '2019-07-25', 'payment_hist_string': '000000000000000014044000000000000000000000000000', 'uid': 'AAA09044550'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,"{'credit_type': 'Credit card', 'loan_amount': 80996.445, 'amount_overdue': 0.0, 'open_date': '2020-06-29', 'closed_date': None, 'payment_hist_string': '000000000000000000', 'uid': 'AAA10545297'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,"{'credit_type': 'Consumer credit', 'loan_amount': 43771.5, 'amount_overdue': 0.0, 'open_date': '2020-06-09', 'closed_date': '2020-09-09', 'payment_hist_string': '000000000', 'uid': 'AAA14112888'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,"{'credit_type': 'Credit card', 'loan_amount': 10480.5, 'amount_overdue': 0.0, 'open_date': '2014-09-10', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000017047077107137167197227257287317347377407437467497527557587617647677707737767797827857887917000000000000', 'uid': 'AAA20326915'}","{'credit_type': 'Consumer credit', 'loan_amount': 46696.5, 'amount_overdue': 0.0, 'open_date': '2016-11-20', 'closed_date': '2017-10-06', 'payment_hist_string': '000000000000000000000000000000', 'uid': 'AAA20326915'}","{'credit_type': 'Credit card', 'loan_amount': 0.0, 'amount_overdue': 0.0, 'open_date': '2014-09-10', 'closed_date': '2018-08-30', 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAA20326915'}","{'credit_type': 'Consumer credit', 'loan_amount': 117000.0, 'amount_overdue': 0.0, 'open_date': '2018-02-04', 'closed_date': '2018-05-06', 'payment_hist_string': '000000000', 'uid': 'AAA20326915'}","{'credit_type': 'Consumer credit', 'loan_amount': 90000.0, 'amount_overdue': 0.0, 'open_date': '2020-03-12', 'closed_date': '2020-04-12', 'payment_hist_string': '000', 'uid': 'AAA20326915'}","{'credit_type': 'Consumer credit', 'loan_amount': 235800.0, 'amount_overdue': 0.0, 'open_date': '2020-03-29', 'closed_date': '2020-05-13', 'payment_hist_string': '000', 'uid': 'AAA20326915'}","{'credit_type': 'Consumer credit', 'loan_amount': 46620.0, 'amount_overdue': 0.0, 'open_date': '2020-06-22', 'closed_date': None, 'payment_hist_string': '000000000000000000', 'uid': 'AAA20326915'}","{'credit_type': 'Credit card', 'loan_amount': 45000.0, 'amount_overdue': 0.0, 'open_date': '2020-06-28', 'closed_date': None, 'payment_hist_string': '000000000000000000', 'uid': 'AAA20326915'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,"{'credit_type': 'Consumer credit', 'loan_amount': 687150.0, 'amount_overdue': 0.0, 'open_date': '2020-10-10', 'closed_date': None, 'payment_hist_string': '000000', 'uid': 'AAA31604840'}","{'credit_type': 'Consumer credit', 'loan_amount': 41845.5, 'amount_overdue': 0.0, 'open_date': '2017-02-15', 'closed_date': '2018-02-28', 'payment_hist_string': '000000000000000000000000000000000000', 'uid': 'AAA31604840'}","{'credit_type': 'Consumer credit', 'loan_amount': 468000.0, 'amount_overdue': 0.0, 'open_date': '2017-06-09', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAA31604840'}","{'credit_type': 'Consumer credit', 'loan_amount': 304965.0, 'amount_overdue': 0.0, 'open_date': '2019-04-15', 'closed_date': '2020-10-15', 'payment_hist_string': '000000000000000000000000000000000000000000000000000000', 'uid': 'AAA31604840'}","{'credit_type': 'Credit card', 'loan_amount': 90000.0, 'amount_overdue': 0.0, 'open_date': '2020-09-16', 'closed_date': None, 'payment_hist_string': '000000000', 'uid': 'AAA31604840'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [10]:
accounts.notnull().sum(axis=1).describe()

count    223918.000000
mean          5.561456
std           4.384241
min           1.000000
25%           2.000000
50%           4.000000
75%           8.000000
max         116.000000
dtype: float64

In [11]:
records = []

for _,row in accounts.iterrows():
    for value in row: 
        if isinstance(value, dict):
            records.append(value)

accounts_long = pd.DataFrame(records)

print("Accounts Actual Shape:", accounts_long.shape)
accounts_long.head()

Accounts Actual Shape: (1245310, 7)

,credit_type,loan_amount,amount_overdue,open_date,closed_date,payment_hist_string,uid
0,Consumer credit,272745.000,0.0,2018-09-22,2020-02-22,000000000000000000000010000000000000000000000000000,AAA09044550
1,Consumer credit,4500.000,0.0,2018-03-08,2019-07-25,000000000000000014044000000000000000000000000000,AAA09044550
2,Credit card,80996.445,0.0,2020-06-29,NaN,000000000000000000,AAA10545297
3,Consumer credit,43771.500,0.0,2020-06-09,2020-09-09,000000000,AAA14112888
4,Credit card,10480.500,0.0,2014-09-10,NaN,000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000017047077107137167197227257287317347377407437467497527557587617647677707737767797827857887917000000000000,AAA20326915

In [12]:
accounts_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 1245310 entries, 0 to 1245309
Data columns (total 7 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   credit_type          1245310 non-null  str
 1   loan_amount          1245307 non-null  float64
 2   amount_overdue       1245310 non-null  float64
 3   open_date            1245310 non-null  str
 4   closed_date          782275 non-null   str
 5   payment_hist_string  1245310 non-null  str
 6   uid                  1245310 non-null  str
dtypes: float64(2), str(5)
memory usage: 173.6 MB

In [13]:
accounts_long["uid"].nunique()
#carefully transformation done

223918

In [14]:
loan_counts = (accounts_long.groupby("uid").size())

loan_counts.describe()

count    223918.000000
mean          5.561456
std           4.384241
min           1.000000
25%           2.000000
50%           4.000000
75%           8.000000
max         116.000000
dtype: float64

In [15]:
accounts_long["open_date"] = pd.to_datetime(accounts_long["open_date"])
accounts_long["closed_date"] = pd.to_datetime(accounts_long["closed_date"])

In [16]:
accounts_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 1245310 entries, 0 to 1245309
Data columns (total 7 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   credit_type          1245310 non-null  str
 1   loan_amount          1245307 non-null  float64
 2   amount_overdue       1245310 non-null  float64
 3   open_date            1245310 non-null  datetime64[us]
 4   closed_date          782275 non-null   datetime64[us]
 5   payment_hist_string  1245310 non-null  str
 6   uid                  1245310 non-null  str
dtypes: datetime64[us](2), float64(2), str(3)
memory usage: 154.1 MB

In [17]:
accounts_long["credit_type"].value_counts()

credit_type
Consumer credit                                 908741
Credit card                                     292422
Car loan                                         20237
Mortgage                                         13196
Microloan                                         7766
Loan for business development                     1466
Another type of loan                               732
Unknown type of loan                               374
Loan for working capital replenishment             320
Real estate loan                                    17
Cash loan (non-earmarked)                           17
Loan for the purchase of equipment                  16
Loan for purchase of shares (margin lending)         4
Interbank credit                                     1
Mobile operator loan                                 1
Name: count, dtype: int64

In [18]:
accounts_long.to_csv("../data/accounts_long.csv",  index=False )

In [19]:
enquiry = pd.read_json("../data/enquiry_data_train.json")

print("Enquiry Shape:", enquiry.shape)
enquiry.head()

Enquiry Shape: (261383, 69)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68
0,"{'enquiry_type': 'Interbank credit', 'enquiry_amt': 168839, 'enquiry_date': '2020-11-08', 'uid': 'AAA08065248'}","{'enquiry_type': 'Mobile operator loan', 'enquiry_amt': 268392, 'enquiry_date': '2020-09-20', 'uid': 'AAA08065248'}","{'enquiry_type': 'Mobile operator loan', 'enquiry_amt': 36082, 'enquiry_date': '2020-06-19', 'uid': 'AAA08065248'}","{'enquiry_type': 'Interbank credit', 'enquiry_amt': 180467, 'enquiry_date': '2019-10-22', 'uid': 'AAA08065248'}","{'enquiry_type': 'Cash loan (non-earmarked)', 'enquiry_amt': 227459, 'enquiry_date': '2020-05-24', 'uid': 'AAA08065248'}","{'enquiry_type': 'Mortgage', 'enquiry_amt': 44841, 'enquiry_date': '2019-11-03', 'uid': 'AAA08065248'}","{'enquiry_type': 'Revolving loans', 'enquiry_amt': 364751, 'enquiry_date': '2020-02-26', 'uid': 'AAA08065248'}","{'enquiry_type': 'Interbank credit', 'enquiry_amt': 127618, 'enquiry_date': '2020-10-04', 'uid': 'AAA08065248'}","{'enquiry_type': 'Loan for purchase of shares (margin lending)', 'enquiry_amt': 315591, 'enquiry_date': '2019-06-12', 'uid': 'AAA08065248'}","{'enquiry_type': 'Revolving loans', 'enquiry_amt': 169056, 'enquiry_date': '2019-03-01', 'uid': 'AAA08065248'}","{'enquiry_type': 'Loan for purchase of shares (margin lending)', 'enquiry_amt': 161562, 'enquiry_date': '2020-12-30', 'uid': 'AAA08065248'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,"{'enquiry_type': 'Cash loans', 'enquiry_amt': 120000, 'enquiry_date': '2019-08-19', 'uid': 'AAA09044550'}","{'enquiry_type': 'Interbank credit', 'enquiry_amt': 197000, 'enquiry_date': '2019-11-01', 'uid': 'AAA09044550'}","{'enquiry_type': 'Car loan', 'enquiry_amt': 127000, 'enquiry_date': '2020-06-21', 'uid': 'AAA09044550'}","{'enquiry_type': 'Revolving loans', 'enquiry_amt': 94000, 'enquiry_date': '2020-06-11', 'uid': 'AAA09044550'}","{'enquiry_type': 'Car loan', 'enquiry_amt': 120000, 'enquiry_date': '2020-10-19', 'uid': 'AAA09044550'}","{'enquiry_type': 'Another type of loan', 'enquiry_amt': 174000, 'enquiry_date': '2020-09-29', 'uid': 'AAA09044550'}","{'enquiry_type': 'Loan for the purchase of equipment', 'enquiry_amt': 87000, 'enquiry_date': '2020-10-19', 'uid': 'AAA09044550'}","{'enquiry_type': 'Real estate loan', 'enquiry_amt': 65000, 'enquiry_date': '2017-10-17', 'uid': 'AAA09044550'}","{'enquiry_type': 'Credit card', 'enquiry_amt': 149000, 'enquiry_date': '2018-09-27', 'uid': 'AAA09044550'}","{'enquiry_type': 'Unknown type of loan', 'enquiry_amt': 98000, 'enquiry_date': '2020-10-19', 'uid': 'AAA09044550'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 125000, 'enquiry_date': '2020-12-29', 'uid': 'AAA09044550'}","{'enquiry_type': 'Another type of loan', 'enquiry_amt': 119000, 'enquiry_date': '2019-08-27', 'uid': 'AAA09044550'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 156000, 'enquiry_date': '2020-04-11', 'uid': 'AAA09044550'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 143000, 'enquiry_date': '2020-12-07', 'uid': 'AAA09044550'}","{'enquiry_type': 'Another type of loan', 'enquiry_amt': 24000, 'enquiry_date': '2020-05-21', 'uid': 'AAA09044550'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 90000, 'enquiry_date': '2020-03-25', 'uid': 'AAA09044550'}","{'enquiry_type': 'Microloan', 'enquiry_amt': 41000, 'enquiry_date': '2019-02-05', 'uid': 'AAA09044550'}","{'enquiry_type': 'Consumer credit', 'enquiry_amt': 111000, 'enquiry_date': '2020-12-11', 'uid': 'AAA09044550'}","{'enquiry_type': 'Microloan', 'enquiry_amt': 9000, 'enquiry_date': '2020-07-22', 'uid': 'AAA09044550'}","{'enquiry_type': 'Interbank credit', 'enquiry_amt': 86000, 'enquiry_date': '2020-10-18', 'uid': 'AAA09044550'}","{'enquiry_type': 'Car loan', 'enquiry_amt': 5000, 'enquiry_date': '2020-07-01', 'uid': 'AAA09044550'}","{'enquiry_type': 'Mortgage', 'enquiry_amt': 32000, 'enquiry_date': '2020-09-15', 'uid': 'AAA09044550'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 85000, 'enquiry_date': '2020-05-29', 'uid': 'AAA09044550'}","{'enquiry_type': 'Cash loan (non-earmarked)', 'enquiry_amt': 139000, 'enquiry_date': '2020-05-11', 'uid': 'AAA09044550'}","{'enquiry_type': 'Mobile operator loan', 'enquiry_amt': 102000, 'enquiry_date': '2020-03-12', 'uid': 'AAA09044550'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 161000, 'enquiry_date': '2019-05-12', 'uid': 'AAA09044550'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,"{'enquiry_type': 'Revolving loans', 'enquiry_amt': 94000, 'enquiry_date': '2019-04-22', 'uid': 'AAA10545297'}","{'enquiry_type': 'Consumer credit', 'enquiry_amt': 192000, 'enquiry_date': '2020-01-04', 'uid': 'AAA10545297'}","{'enquiry_type': 'Interbank credit', 'enquiry_amt': 24000, 'enquiry_date': '2020-03-23', 'uid': 'AAA10545297'}","{'enquiry_type': 'Revolving loans', 'enquiry_amt': 5000, 'enquiry_date': '2020-07-12', 'uid': 'AAA10545297'}","{'enquiry_type': 'Loan for purchase of shares (margin lending)', 'enquiry_amt': 58000, 'enquiry_date': '2020-02-28', 'uid': 'AAA10545297'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 65000, 'enquiry_date': '2019-03-15', 'uid': 'AAA10545297'}","{'enquiry_type': 'Cash loan (non-earmarked)', 'enquiry_amt': 9000, 'enquiry_date': '2020-10-29', 'uid': 'AAA10545297'}","{'enquiry_type': 'Another type of loan', 'enquiry_amt': 126000, 'enquiry_date': '2020-09-27', 'uid': 'AAA10545297'}","{'enquiry_type': 'Consumer credit', 'enquiry_amt': 18000, 'enquiry_date': '2020-09-16', 'uid': 'AAA10545297'}","{'enquiry_type': 'Credit card', 'enquiry_amt': 142000, 'enquiry_date': '2019-12-26', 'uid': 'AAA10545297'}","{'enquiry_type': 'Cash loan (non-earmarked)', 'enquiry_amt': 183000, 'enquiry_date': '2020-06-02', 'uid': 'AAA10545297'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 173000, 'enquiry_date': '2019-08-26', 'uid': 'AAA10545297'}","{'enquiry_type': 'Unknown type of loan', 'enquiry_amt': 134000, 'enquiry_date': '2020-01-01', 'uid': 'AAA10545297'}","{'enquiry_type': 'Credit card', 'enquiry_amt': 94000, 'enquiry_date': '2018-07-06', 'uid': 'AAA10545297'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,"{'enquiry_type': 'Loan for purchase of shares (margin lending)', 'enquiry_amt': 39000, 'enquiry_date': '2019-11-09', 'uid': 'AAA14112888'}","{'enquiry_type': 'Loan for working capital replenishment', 'enquiry_amt': 110000, 'enquiry_date': '2020-04-03', 'uid': 'AAA14112888'}","{'enquiry_type': 'Consumer credit', 'enquiry_amt': 62000, 'enquiry_date': '2020-03-10', 'uid': 'AAA14112888'}","{'enquiry_type': 'Loan for the purchase of equipment', 'enquiry_amt': 171000, 'enquiry_date': '2019-07-11', 'uid': 'AAA14112888'}","{'enquiry_type': 'Another type of loan', 'enquiry_amt': 185000, 'enquiry_date': '2020-04-19', 'uid': 'AAA14112888'}","{'enquiry_type': 'Loan for the purchase of equipment', 'enquiry_amt': 45000, 'enquiry_date': '2020-06-25', 'uid': 'AAA14112888'}","{'enquiry_type': 'Unknown type of loan', 'enquiry_amt': 17000, 'enquiry_date': '2020-04-15', 'uid': 'AAA14112888'}","{'enquiry_type': 'Cash loan (non-earmarked)', 'enquiry_amt': 95000, 'enquiry_date': '2019-11-24', 'uid': 'AAA14112888'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 94000, 'enquiry_date': '2019-03-02', 'uid': 'AAA14112888'}","{'enquiry_type': 'Consumer credit', 'enquiry_amt': 84000, 'enquiry_date': '2018-01-06', 'uid': 'AAA14112888'}","{'enquiry_type': 'Mobile operator loan', 'enquiry_amt': 120000, 'enquiry_date': '2017-04-13', 'uid': 'AAA14112888'}","{'enquiry_type': 'Mobile operator loan', 'enquiry_amt': 129000, 'enquiry_date': '2020-07-01', 'uid': 'AAA14112888'}","{'enquiry_type': 'Interbank credit', 'enquiry_amt': 112000, 'enquiry_date': '2019-12-06', 'uid': 'AAA14112888'}","{'enquiry_type': 'Loan for purchase of shares (margin lending)', 'enquiry_amt': 52000, 'enquiry_date': '2020-07-05', 'uid': 'AAA14112888'}","{'enquiry_type': 'Loan for working capital replenishment', 'enquiry_amt': 150000, 'enquiry_date': '2019-11-10', 'uid': 'AAA14112888'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,"{'enquiry_type': 'Mobile operator loan', 'enquiry_amt': 66000, 'enquiry_date': '2020-08-14', 'uid': 'AAA20326915'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [20]:
records = []

for _,row in enquiry.iterrows():
    for value in row: 
        if isinstance(value, dict):
            records.append(value)

enquiry_long = pd.DataFrame(records)

print("Enquiry Actual Shape:", enquiry_long.shape)
enquiry_long.head()

Enquiry Actual Shape: (1909926, 4)

                enquiry_type  enquiry_amt enquiry_date          uid
0           Interbank credit       168839   2020-11-08  AAA08065248
1       Mobile operator loan       268392   2020-09-20  AAA08065248
2       Mobile operator loan        36082   2020-06-19  AAA08065248
3           Interbank credit       180467   2019-10-22  AAA08065248
4  Cash loan (non-earmarked)       227459   2020-05-24  AAA08065248

In [21]:
enquiry_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 1909926 entries, 0 to 1909925
Data columns (total 4 columns):
 #   Column        Dtype
---  ------        -----
 0   enquiry_type  str
 1   enquiry_amt   int64
 2   enquiry_date  str
 3   uid           str
dtypes: int64(1), str(3)
memory usage: 130.7 MB

In [22]:
enquiry_long.notnull().sum(axis=1).describe()
# no null values

count    1909926.0
mean           4.0
std            0.0
min            4.0
25%            4.0
50%            4.0
75%            4.0
max            4.0
dtype: float64

In [23]:
enquiry_long["uid"].nunique() # all unique uid fetched

261383

In [24]:
enquiry_long["enquiry_date"] = pd.to_datetime(enquiry_long["enquiry_date"])

In [25]:
enquiry_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 1909926 entries, 0 to 1909925
Data columns (total 4 columns):
 #   Column        Dtype
---  ------        -----
 0   enquiry_type  str
 1   enquiry_amt   int64
 2   enquiry_date  datetime64[us]
 3   uid           str
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 112.5 MB

In [26]:
enquiry_long["enquiry_type"].value_counts().head(20)

enquiry_type
Cash loans                                      303108
Revolving loans                                 120181
Mobile operator loan                             99479
Real estate loan                                 99328
Microloan                                        99324
Unknown type of loan                             99280
Loan for purchase of shares (margin lending)     99230
Mortgage                                         99216
Credit card                                      99208
Another type of loan                             99154
Loan for the purchase of equipment               99152
Interbank credit                                 99063
Car loan                                         98994
Loan for business development                    98900
Cash loan (non-earmarked)                        98831
Loan for working capital replenishment           98814
Consumer credit                                  98664
Name: count, dtype: int64

In [27]:
enquiry_long.to_csv("../data/enquiry_long.csv",  index=False )

In [258]:
# For Test Data Transformation

accounts_test = pd.read_json("../data/accounts_data_test.json")

print("Accounts Shape:", accounts_test.shape)
accounts_test.head()

Accounts Shape: (39572, 49)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48
0,"{'credit_type': 'Consumer credit', 'loan_amount': 31630.5, 'amount_overdue': 0.0, 'open_date': '2014-03-30', 'closed_date': '2014-11-29', 'payment_hist_string': '000000000000000000000000', 'uid': 'AAA14437029'}","{'credit_type': 'Consumer credit', 'loan_amount': 14613.39, 'amount_overdue': 0.0, 'open_date': '2014-06-01', 'closed_date': '2014-11-03', 'payment_hist_string': '000000000000000', 'uid': 'AAA14437029'}","{'credit_type': 'Credit card', 'loan_amount': 54000.0, 'amount_overdue': 0.0, 'open_date': '2015-12-13', 'closed_date': '2019-09-21', 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAA14437029'}","{'credit_type': 'Consumer credit', 'loan_amount': 27076.5, 'amount_overdue': 0.0, 'open_date': '2015-11-11', 'closed_date': '2016-11-24', 'payment_hist_string': '000000000000000000000000000000000000', 'uid': 'AAA14437029'}","{'credit_type': 'Credit card', 'loan_amount': 225000.0, 'amount_overdue': 0.0, 'open_date': '2017-07-15', 'closed_date': '2019-11-14', 'payment_hist_string': '000000000000000000000000000000000000000000000000000015045075105135165195225255285000', 'uid': 'AAA14437029'}","{'credit_type': 'Consumer credit', 'loan_amount': 1575000.0, 'amount_overdue': 0.0, 'open_date': '2016-12-05', 'closed_date': '2017-07-03', 'payment_hist_string': '000000000000000000000', 'uid': 'AAA14437029'}","{'credit_type': 'Credit card', 'loan_amount': 58347.0, 'amount_overdue': 0.0, 'open_date': '2016-06-21', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAA14437029'}","{'credit_type': 'Credit card', 'loan_amount': 42750.0, 'amount_overdue': 0.0, 'open_date': '2019-10-26', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000', 'uid': 'AAA14437029'}","{'credit_type': 'Consumer credit', 'loan_amount': 135000.0, 'amount_overdue': 0.0, 'open_date': '2016-07-24', 'closed_date': '2016-12-05', 'payment_hist_string': '000000000000', 'uid': 'AAA14437029'}","{'credit_type': 'Credit card', 'loan_amount': 67500.0, 'amount_overdue': 0.0, 'open_date': '2014-09-18', 'closed_date': '2016-06-21', 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAA14437029'}","{'credit_type': 'Consumer credit', 'loan_amount': 1478322.0, 'amount_overdue': 0.0, 'open_date': '2017-07-03', 'closed_date': '2019-11-11', 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAA14437029'}","{'credit_type': 'Consumer credit', 'loan_amount': 27076.5, 'amount_overdue': 0.0, 'open_date': '2015-11-12', 'closed_date': '2016-11-11', 'payment_hist_string': '000000000000000000000000000000000000', 'uid': 'AAA14437029'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,"{'credit_type': 'Consumer credit', 'loan_amount': 45532.98, 'amount_overdue': 0.0, 'open_date': '2016-03-26', 'closed_date': '2016-09-24', 'payment_hist_string': '000006036000000000', 'uid': 'AAB12915377'}","{'credit_type': 'Consumer credit', 'loan_amount': 114975.0, 'amount_overdue': 0.0, 'open_date': '2017-07-05', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAB12915377'}","{'credit_type': 'Credit card', 'loan_amount': 247500.0, 'amount_overdue': 0.0, 'open_date': '2019-02-06', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAB12915377'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,"{'credit_type': 'Consumer credit', 'loan_amount': 62086.275, 'amount_overdue': 0.0, 'open_date': '2019-04-30', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAB55088883'}","{'credit_type': 'Consumer credit', 'loan_amount': 46204.65, 'amount_overdue': 0.0, 'open_date': '2013-08-27', 'closed_date': '2014-01-27', 'payment_hist_string': '000000000000000', 'uid': 'AAB55088883'}","{'credit_type': 'Consumer credit', 'loan_amount': 57266.91, 'amount_overdue': 0.0, 'open_date': '2014-12-25', 'closed_date': '2015-06-29', 'payment_hist_string': '000000000000000000', 'uid': 'AAB55088883'}","{'credit_type': 'Consumer credit', 'loan_amount': 114471.9, 'amount_overdue': 0.0, 'open_date': '2017-05-14', 'closed_date': '2018-03-16', 'payment_hist_string': '000000000000000000000000000000', 'uid': 'AAB55088883'}","{'credit_type': 'Consumer credit', 'loan_amount': 42864.75, 'amount_overdue': 0.0, 'open_date': '2017-10-12', 'closed_date': '2018-07-15', 'payment_hist_string': '000000000000000000000000000', 'uid': 'AAB55088883'}","{'credit_type': 'Credit card', 'loan_amount': 4500.0, 'amount_overdue': 0.0, 'open_date': '2019-04-30', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAB55088883'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,"{'credit_type': 'Consumer credit', 'loan_amount': 417600.0, 'amount_overdue': 0.0, 'open_date': '2019-01-24', 'closed_date': '2020-10-27', 'payment_hist_string': '000000000000000000000000000000018048078108138168198228000000000', 'uid': 'AAB68152393'}","{'credit_type': 'Credit card', 'loan_amount': 166500.0, 'amount_overdue': 0.0, 'open_date': '2019-01-24', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAB68152393'}","{'credit_type': 'Consumer credit', 'loan_amount': 88587.0, 'amount_overdue': 0.0, 'open_date': '2015-05-14', 'closed_date': '2016-03-16', 'payment_hist_string': '000000000000000000000000000000', 'uid': 'AAB68152393'}","{'credit_type': 'Consumer credit', 'loan_amount': 63049.5, 'amount_overdue': 0.0, 'open_date': '2014-05-03', 'closed_date': '2015-10-27', 'payment_hist_string': '000000000000000000000000000000000000000000000000000000', 'uid': 'AAB68152393'}","{'credit_type': 'Credit card', 'loan_amount': 135000.0, 'amount_overdue': 0.0, 'open_date': '2019-11-20', 'closed_date': '2020-06-15', 'payment_hist_string': '000000000000000000', 'uid': 'AAB68152393'}","{'credit_type': 'Consumer credit', 'loan_amount': 711000.0, 'amount_overdue': 0.0, 'open_date': '2018-01-05', 'closed_date': '2020-09-18', 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAB68152393'}","{'credit_type': 'Credit card', 'loan_amount': 225000.0, 'amount_overdue': 0.0, 'open_date': '2018-10-13', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAB68152393'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,"{'credit_type': 'Consumer credit', 'loan_amount': 42436.8, 'amount_overdue': 0.0, 'open_date': '2016-01-18', 'closed_date': '2017-01-18', 'payment_hist_string': '000000000000000000000000000000000000', 'uid': 'AAC29580834'}","{'credit_type': 'Consumer credit', 'loan_amount': 637740.0, 'amount_overdue': 0.0, 'open_date': '2017-10-10', 'closed_date': '2018-12-30', 'payment_hist_string': '000000000000000000000000000000000000000000', 'uid': 'AAC29580834'}","{'credit_type': 'Consumer credit', 'loan_amount': 1422000.0, 'amount_overdue': 0.0, 'open_date': '2019-05-02', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000000000000000000000000000', 'uid': 'AAC29580834'}","{'credit_type': 'Consumer credit', 'loan_amount': 40860.0, 'amount_overdue': 0.0, 'open_date': '2020-01-02', 'closed_date': None, 'payment_hist_string': '000000000000000000000000000000000000', 'uid': 'AAC29580834'}","{'credit_type': 'Consumer credit', 'loan_amount': 724500.0, 'amount_overdue': 0.0, 'open_date': '2020-08-15', 'closed_date': None, 'payment_hist_string': '000000000000', 'uid': 'AAC29580834'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [259]:
accounts_test.notnull().sum(axis=1).describe()

count   39572.00
mean        5.56
std         4.34
min         1.00
25%         2.00
50%         4.00
75%         8.00
max        49.00
dtype: float64

In [260]:
records = []

for _,row in accounts_test.iterrows():
    for value in row: 
        if isinstance(value, dict):
            records.append(value)

accounts_test_long = pd.DataFrame(records)

print("Accounts Actual Shape:", accounts_test_long.shape)
accounts_test_long.head()

Accounts Actual Shape: (220013, 7)

,credit_type,loan_amount,amount_overdue,open_date,closed_date,payment_hist_string,uid
0,Consumer credit,31630.50,0.00,2014-03-30,2014-11-29,000000000000000000000000,AAA14437029
1,Consumer credit,14613.39,0.00,2014-06-01,2014-11-03,000000000000000,AAA14437029
2,Credit card,54000.00,0.00,2015-12-13,2019-09-21,000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,AAA14437029
3,Consumer credit,27076.50,0.00,2015-11-11,2016-11-24,000000000000000000000000000000000000,AAA14437029
4,Credit card,225000.00,0.00,2017-07-15,2019-11-14,000000000000000000000000000000000000000000000000000015045075105135165195225255285000,AAA14437029

In [261]:
accounts_test_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 220013 entries, 0 to 220012
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   credit_type          220013 non-null  str
 1   loan_amount          220013 non-null  float64
 2   amount_overdue       220013 non-null  float64
 3   open_date            220013 non-null  str
 4   closed_date          138377 non-null  str
 5   payment_hist_string  220013 non-null  str
 6   uid                  220013 non-null  str
dtypes: float64(2), str(5)
memory usage: 30.7 MB

In [264]:
loan_test_counts = (accounts_test_long.groupby("uid").size())

loan_test_counts.describe()

count   39572.00
mean        5.56
std         4.34
min         1.00
25%         2.00
50%         4.00
75%         8.00
max        49.00
dtype: float64

In [262]:
accounts_test_long["open_date"] = pd.to_datetime(accounts_test_long["open_date"])
accounts_test_long["closed_date"] = pd.to_datetime(accounts_test_long["closed_date"])

In [263]:
accounts_test_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 220013 entries, 0 to 220012
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   credit_type          220013 non-null  str
 1   loan_amount          220013 non-null  float64
 2   amount_overdue       220013 non-null  float64
 3   open_date            220013 non-null  datetime64[us]
 4   closed_date          138377 non-null  datetime64[us]
 5   payment_hist_string  220013 non-null  str
 6   uid                  220013 non-null  str
dtypes: datetime64[us](2), float64(2), str(3)
memory usage: 27.2 MB

In [265]:
accounts_test_long.to_csv("../data/accounts_test_long.csv",  index=False )

In [266]:
enquiry_test = pd.read_json("../data/enquiry_data_test.json")

print("Enquiry Test Shape:", enquiry_test.shape)
enquiry_test.head()

Enquiry Test Shape: (46127, 56)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55
0,"{'enquiry_type': 'Car loan', 'enquiry_amt': 143000, 'enquiry_date': '2020-12-13', 'uid': 'AAA02107680'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,"{'enquiry_type': 'Real estate loan', 'enquiry_amt': 174000, 'enquiry_date': '2020-12-01', 'uid': 'AAA14437029'}","{'enquiry_type': 'Loan for working capital replenishment', 'enquiry_amt': 65000, 'enquiry_date': '2019-07-01', 'uid': 'AAA14437029'}","{'enquiry_type': 'Loan for working capital replenishment', 'enquiry_amt': 118000, 'enquiry_date': '2020-08-05', 'uid': 'AAA14437029'}","{'enquiry_type': 'Car loan', 'enquiry_amt': 12000, 'enquiry_date': '2020-02-28', 'uid': 'AAA14437029'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,"{'enquiry_type': 'Real estate loan', 'enquiry_amt': 137000, 'enquiry_date': '2019-11-11', 'uid': 'AAB12915377'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,"{'enquiry_type': 'Unknown type of loan', 'enquiry_amt': 129000, 'enquiry_date': '2020-09-06', 'uid': 'AAB55088883'}","{'enquiry_type': 'Loan for the purchase of equipment', 'enquiry_amt': 30000, 'enquiry_date': '2018-11-28', 'uid': 'AAB55088883'}","{'enquiry_type': 'Real estate loan', 'enquiry_amt': 6000, 'enquiry_date': '2020-09-15', 'uid': 'AAB55088883'}","{'enquiry_type': 'Mortgage', 'enquiry_amt': 79000, 'enquiry_date': '2019-09-22', 'uid': 'AAB55088883'}","{'enquiry_type': 'Another type of loan', 'enquiry_amt': 28000, 'enquiry_date': '2019-05-23', 'uid': 'AAB55088883'}","{'enquiry_type': 'Cash loan (non-earmarked)', 'enquiry_amt': 165000, 'enquiry_date': '2020-08-28', 'uid': 'AAB55088883'}","{'enquiry_type': 'Loan for business development', 'enquiry_amt': 113000, 'enquiry_date': '2020-12-29', 'uid': 'AAB55088883'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 6000, 'enquiry_date': '2020-11-28', 'uid': 'AAB55088883'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 12000, 'enquiry_date': '2020-04-04', 'uid': 'AAB55088883'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 74000, 'enquiry_date': '2019-04-02', 'uid': 'AAB55088883'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 176000, 'enquiry_date': '2019-07-25', 'uid': 'AAB55088883'}","{'enquiry_type': 'Unknown type of loan', 'enquiry_amt': 79000, 'enquiry_date': '2020-05-26', 'uid': 'AAB55088883'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 77000, 'enquiry_date': '2020-07-19', 'uid': 'AAB55088883'}","{'enquiry_type': 'Microloan', 'enquiry_amt': 131000, 'enquiry_date': '2020-04-18', 'uid': 'AAB55088883'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,"{'enquiry_type': 'Cash loans', 'enquiry_amt': 162000, 'enquiry_date': '2020-04-24', 'uid': 'AAB68152393'}","{'enquiry_type': 'Real estate loan', 'enquiry_amt': 179000, 'enquiry_date': '2019-08-14', 'uid': 'AAB68152393'}","{'enquiry_type': 'Cash loans', 'enquiry_amt': 127000, 'enquiry_date': '2020-10-29', 'uid': 'AAB68152393'}","{'enquiry_type': 'Credit card', 'enquiry_amt': 59000, 'enquiry_date': '2020-11-19', 'uid': 'AAB68152393'}","{'enquiry_type': 'Loan for business development', 'enquiry_amt': 117000, 'enquiry_date': '2020-11-12', 'uid': 'AAB68152393'}","{'enquiry_type': 'Loan for working capital replenishment', 'enquiry_amt': 142000, 'enquiry_date': '2020-04-14', 'uid': 'AAB68152393'}","{'enquiry_type': 'Loan for business development', 'enquiry_amt': 52000, 'enquiry_date': '2020-07-30', 'uid': 'AAB68152393'}","{'enquiry_type': 'Consumer credit', 'enquiry_amt': 120000, 'enquiry_date': '2018-05-04', 'uid': 'AAB68152393'}","{'enquiry_type': 'Revolving loans', 'enquiry_amt': 185000, 'enquiry_date': '2019-10-26', 'uid': 'AAB68152393'}","{'enquiry_type': 'Loan for the purchase of equipment', 'enquiry_amt': 159000, 'enquiry_date': '2020-07-24', 'uid': 'AAB68152393'}","{'enquiry_type': 'Loan for working capital replenishment', 'enquiry_amt': 9000, 'enquiry_date': '2019-10-15', 'uid': 'AAB68152393'}","{'enquiry_type': 'Unknown type of loan', 'enquiry_amt': 186000, 'enquiry_date': '2021-01-01', 'uid': 'AAB68152393'}","{'enquiry_type': 'Mobile operator loan', 'enquiry_amt': 162000, 'enquiry_date': '2019-12-26', 'uid': 'AAB68152393'}","{'enquiry_type': 'Revolving loans', 'enquiry_amt': 60000, 'enquiry_date': '2019-12-15', 'uid': 'AAB68152393'}","{'enquiry_type': 'Another type of loan', 'enquiry_amt': 141000, 'enquiry_date': '2020-10-01', 'uid': 'AAB68152393'}","{'enquiry_type': 'Interbank credit', 'enquiry_amt': 62000, 'enquiry_date': '2018-08-28', 'uid': 'AAB68152393'}","{'enquiry_type': 'Loan for purchase of shares (margin lending)', 'enquiry_amt': 65000, 'enquiry_date': '2020-07-08', 'uid': 'AAB68152393'}",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [267]:
records = []

for _,row in enquiry_test.iterrows():
    for value in row: 
        if isinstance(value, dict):
            records.append(value)

enquiry_test_long = pd.DataFrame(records)

print("Enquiry Test Shape:", enquiry_test_long.shape)
enquiry_test_long.head()

Enquiry Test Shape: (337662, 4)

,enquiry_type,enquiry_amt,enquiry_date,uid
0,Car loan,143000,2020-12-13,AAA02107680
1,Real estate loan,174000,2020-12-01,AAA14437029
2,Loan for working capital replenishment,65000,2019-07-01,AAA14437029
3,Loan for working capital replenishment,118000,2020-08-05,AAA14437029
4,Car loan,12000,2020-02-28,AAA14437029

In [269]:
enquiry_test_long["enquiry_date"] = pd.to_datetime(enquiry_test_long["enquiry_date"])

In [270]:
enquiry_test_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 337662 entries, 0 to 337661
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   enquiry_type  337662 non-null  str
 1   enquiry_amt   337662 non-null  int64
 2   enquiry_date  337662 non-null  datetime64[us]
 3   uid           337662 non-null  str
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 19.9 MB

In [271]:
enquiry_test_long.to_csv("../data/enquiry_test_long.csv",  index=False )

In [28]:
# Auditing Data 
print("Train uid: " , train_flag["uid"].nunique() )
print("Account uid: " , accounts_long["uid"].nunique() )
print("Enquiry uid: " , enquiry_long["uid"].nunique() )

Train uid:  261383
Account uid:  223918
Enquiry uid:  261383

In [29]:
train_uid = set(train_flag["uid"])
account_uid = set(accounts_long["uid"]) 
enquiry_uid = set(enquiry_long["uid"])

print("Train: ", len(train_uid))
print("Account:", len(account_uid))
print("Enquiry:", len(enquiry_uid))

Train:  261383
Account: 223918
Enquiry: 261383

In [30]:
# Borrowers not having accounts history

len ( train_uid - account_uid)

37465

In [31]:
# Borrowers not having enquiry history
len ( train_uid - enquiry_uid)

0

In [32]:
# Which Columns having missing value

In [33]:
accounts_missing = ( accounts_long.isnull().mean().mul(100).sort_values(ascending=False))

accounts_missing

closed_date            37.182308
loan_amount             0.000241
credit_type             0.000000
amount_overdue          0.000000
open_date               0.000000
payment_hist_string     0.000000
uid                     0.000000
dtype: float64

In [34]:
enquiry_missing = ( enquiry_long.isnull().mean().mul(100).sort_values(ascending=False))

enquiry_missing

enquiry_type    0.0
enquiry_amt     0.0
enquiry_date    0.0
uid             0.0
dtype: float64

In [35]:
# How much borrowers borrow
pd.set_option('display.float_format', '{:.2f}'.format)
accounts_long["loan_amount"].describe(percentiles=[ .01,.05,.25,.5,.75,.95,.99])

count     1245307.00
mean       352354.12
std       1109811.56
min             0.00
1%              0.00
5%          12379.50
25%         51147.00
50%        124659.00
75%        308700.00
95%       1350000.00
99%       3615515.10
max     396000000.00
Name: loan_amount, dtype: float64

In [272]:
accounts_test_long["loan_amount"].describe(percentiles=[ .01,.05,.25,.5,.75,.95,.99])

count     220013.00
mean      347921.95
std       876513.29
min            0.00
1%             0.00
5%         12836.70
25%        51250.50
50%       124843.50
75%       306000.00
95%      1350000.00
99%      3600000.00
max     58032000.00
Name: loan_amount, dtype: float64

In [36]:
# invalid loan amount
(accounts_long["loan_amount"] <= 0).sum()

np.int64(47585)

In [37]:
# How many loans are overdue 
pd.set_option('display.float_format', '{:.2f}'.format)
accounts_long["amount_overdue"].describe(percentiles=[.01,.05,.25,.5,.75,.95,.99])

count   1245310.00
mean         42.02
std        6668.69
min           0.00
1%            0.00
5%            0.00
25%           0.00
50%           0.00
75%           0.00
95%           0.00
99%           0.00
max     3756681.00
Name: amount_overdue, dtype: float64

In [273]:
accounts_test_long["amount_overdue"].describe(percentiles=[.01,.05,.25,.5,.75,.95,.99])

count   220013.00
mean        29.25
std       3227.89
min          0.00
1%           0.00
5%           0.00
25%          0.00
50%          0.00
75%          0.00
95%          0.00
99%          0.00
max     959386.50
Name: amount_overdue, dtype: float64

In [38]:
# percentage of loans that are overdue
(accounts_long["amount_overdue"] > 0).mean() * 100

np.float64(0.2482112887554103)

In [39]:
accounts_long["is_active"] = (accounts_long[ "closed_date"].isna()).astype(int)

In [274]:
accounts_test_long["is_active"] = (accounts_test_long[ "closed_date"].isna()).astype(int)

In [40]:
# How many loans are active
accounts_long["is_active"].mean() * 100

np.float64(37.18230801968988)

In [275]:
accounts_test_long["is_active"].mean() * 100

np.float64(37.10508015435451)

In [41]:
def parse_dpd(hist):

    if pd.isna(hist) or hist == "":
        return []

    return [
        int(hist[i:i+3])
        for i in range(0, len(hist), 3)
    ]

In [42]:
accounts_long["dpd_list"] = ( accounts_long["payment_hist_string"].apply(parse_dpd))

In [276]:
accounts_test_long["dpd_list"] = ( accounts_test_long["payment_hist_string"].apply(parse_dpd))

In [43]:
accounts_long[["payment_hist_string","dpd_list"]].head(5)

,payment_hist_string,dpd_list
0,000000000000000000000010000000000000000000000000000,"[0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
1,000000000000000014044000000000000000000000000000,"[0, 0, 0, 0, 0, 14, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
2,000000000000000000,"[0, 0, 0, 0, 0, 0]"
3,000000000,"[0, 0, 0]"
4,000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000017047077107137167197227257287317347377407437467497527557587617647677707737767797827857887917000000000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 47, 77, 107, 137, 167, 197, 227, 257, 287, 317, 347, 377, 407, 437, 467, 497, 527, 557, 587, 617, 647, 677, 707, 737, 767, 797, 827, 857, 887, 917, 0, 0, 0, 0]"

In [277]:
accounts_test_long[["payment_hist_string","dpd_list"]].head(5)

,payment_hist_string,dpd_list
0,000000000000000000000000,"[0, 0, 0, 0, 0, 0, 0, 0]"
1,000000000000000,"[0, 0, 0, 0, 0]"
2,000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
3,000000000000000000000000000000000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
4,000000000000000000000000000000000000000000000000000015045075105135165195225255285000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 45, 75, 105, 135, 165, 195, 225, 255, 285, 0]"

In [44]:
accounts_long["dpd_months"] = ( accounts_long["dpd_list"].apply(len))
pd.set_option('display.float_format', '{:.2f}'.format)
accounts_long["dpd_months"].describe(percentiles=[.01,.05,.25,.5,.75,.90,.95,.99])

count   1245310.00
mean         16.30
std          16.33
min           0.00
1%            0.00
5%            1.00
25%           6.00
50%          11.00
75%          22.00
90%          37.00
95%          50.00
99%          82.00
max          97.00
Name: dpd_months, dtype: float64

In [278]:
accounts_test_long["dpd_months"] = ( accounts_test_long["dpd_list"].apply(len))
accounts_test_long["dpd_months"].describe(percentiles=[.01,.05,.25,.5,.75,.90,.95,.99])

count   220013.00
mean        16.31
std         16.34
min          0.00
1%           0.00
5%           1.00
25%          6.00
50%         11.00
75%         22.00
90%         38.00
95%         50.00
99%         83.00
max         97.00
Name: dpd_months, dtype: float64

In [45]:
accounts_long["dpd_months"].describe()

count   1245310.00
mean         16.30
std          16.33
min           0.00
25%           6.00
50%          11.00
75%          22.00
max          97.00
Name: dpd_months, dtype: float64

In [46]:
# worst deliquencies
accounts_long["dpd_max"] = (accounts_long["dpd_list"].apply( lambda x: max(x) if len(x)>0 else 0))

In [279]:
accounts_test_long["dpd_max"] = (accounts_test_long["dpd_list"].apply( lambda x: max(x) if len(x)>0 else 0))

In [47]:
accounts_long["dpd_max"].describe(percentiles=[.50,.75,.90,.95,.99] )

count   1245310.00
mean          7.04
std          44.22
min           0.00
50%           0.00
75%           0.00
90%           0.00
95%          29.00
99%         176.00
max         999.00
Name: dpd_max, dtype: float64

In [48]:
# Recent Payout
accounts_long["dpd_last"] = (accounts_long["dpd_list"].apply( lambda x:x[-1]if len(x)>0 else 0))

In [280]:
accounts_test_long["dpd_last"] = (accounts_test_long["dpd_list"].apply( lambda x:x[-1]if len(x)>0 else 0))

In [49]:
accounts_long["dpd_last"].describe(percentiles=[ .50,.75,.90,.95,.99])

count   1245310.00
mean          0.59
std          21.76
min           0.00
50%           0.00
75%           0.00
90%           0.00
95%           0.00
99%           0.00
max         999.00
Name: dpd_last, dtype: float64

In [50]:
# Overall Riskiness 

accounts_long["dpd_avg"] = (accounts_long["dpd_list"].apply( lambda x:np.mean(x) if len(x)>0 else 0))

In [281]:
accounts_test_long["dpd_avg"] = (accounts_test_long["dpd_list"].apply( lambda x:np.mean(x) if len(x)>0 else 0))

In [51]:
accounts_long["dpd_avg"].describe(percentiles=[.50,.75,.90,.95,.99])

count   1245310.00
mean          1.14
std          10.10
min           0.00
50%           0.00
75%           0.00
90%           0.00
95%           3.17
99%          25.83
max         526.03
Name: dpd_avg, dtype: float64

In [52]:
# How often borrowers are overdue
accounts_long["months_dpd_gt0"] = (accounts_long["dpd_list"].apply(lambda x:sum(v > 0 for v in x)))

In [282]:
accounts_test_long["months_dpd_gt0"] = (accounts_test_long["dpd_list"].apply(lambda x:sum(v > 0 for v in x)))

In [53]:
accounts_long["months_dpd_gt0"].describe(percentiles=[ .50,.75 ,.90,.95,.99])

count   1245310.00
mean          0.28
std           1.60
min           0.00
50%           0.00
75%           0.00
90%           0.00
95%           1.00
99%           6.00
max          81.00
Name: months_dpd_gt0, dtype: float64

In [54]:
accounts_long["months_dpd_gt30"] = (accounts_long["dpd_list"].apply( lambda x:sum(v >= 30 for v in x) ))

In [283]:
accounts_test_long["months_dpd_gt30"] = (accounts_test_long["dpd_list"].apply( lambda x:sum(v >= 30 for v in x) ))

In [55]:
accounts_long["months_dpd_gt60"] = (accounts_long["dpd_list"].apply(lambda x:sum(v >= 60 for v in x)))

In [284]:
accounts_test_long["months_dpd_gt60"] = (accounts_test_long["dpd_list"].apply(lambda x:sum(v >= 60 for v in x)))

In [56]:
accounts_long["months_dpd_gt90"] = (accounts_long["dpd_list"].apply( lambda x:sum(v >= 90 for v in x)))

In [285]:
accounts_test_long["months_dpd_gt90"] = (accounts_test_long["dpd_list"].apply( lambda x:sum(v >= 90 for v in x)))

In [57]:
accounts_long[["months_dpd_gt30", "months_dpd_gt60","months_dpd_gt90"]].describe()

       months_dpd_gt30  months_dpd_gt60  months_dpd_gt90
count       1245310.00       1245310.00       1245310.00
mean              0.20             0.15             0.12
std               1.46             1.33             1.23
min               0.00             0.00             0.00
25%               0.00             0.00             0.00
50%               0.00             0.00             0.00
75%               0.00             0.00             0.00
max              79.00            77.00            75.00

In [58]:
accounts_long["ever_30_plus"] = (accounts_long["dpd_max"] >= 30).astype(int)

accounts_long["ever_60_plus"] = (accounts_long["dpd_max"] >= 60).astype(int)

accounts_long["ever_90_plus"] = (accounts_long["dpd_max"] >= 90).astype(int)

In [286]:
accounts_test_long["ever_30_plus"] = (accounts_test_long["dpd_max"] >= 30).astype(int)

accounts_test_long["ever_60_plus"] = (accounts_test_long["dpd_max"] >= 60).astype(int)

accounts_test_long["ever_90_plus"] = (accounts_test_long["dpd_max"] >= 90).astype(int)

In [59]:
accounts_long[["ever_30_plus","ever_60_plus","ever_90_plus"]].mean()*100

ever_30_plus   4.94
ever_60_plus   3.15
ever_90_plus   2.20
dtype: float64

In [287]:
accounts_test_long[["ever_30_plus","ever_60_plus","ever_90_plus"]].mean()*100

ever_30_plus   4.93
ever_60_plus   3.14
ever_90_plus   2.19
dtype: float64

In [60]:
# Borrowers nature improving or decreasing 
def dpd_trend(x):

    if len(x) < 2:
        return 0

    return x[-1] - x[0]

In [61]:
accounts_long["dpd_trend"] = (accounts_long["dpd_list"].apply(dpd_trend))

In [288]:
accounts_test_long["dpd_trend"] = (accounts_test_long["dpd_list"].apply(dpd_trend))

In [62]:
accounts_long["dpd_trend"].describe(percentiles=[ .01,.05,.25,.5,.75,.95,.99] )

count   1245310.00
mean          0.49
std          21.75
min         -26.00
1%           -3.00
5%            0.00
25%           0.00
50%           0.00
75%           0.00
95%           0.00
99%           0.00
max         999.00
Name: dpd_trend, dtype: float64

In [63]:
accounts_long["recent_3m_avg"] = (accounts_long["dpd_list"].apply( lambda x:np.mean(x[-3:])if len(x) > 0 else 0))

In [289]:
accounts_test_long["recent_3m_avg"] = (accounts_test_long["dpd_list"].apply( lambda x:np.mean(x[-3:])if len(x) > 0 else 0))

In [64]:
accounts_long["recent_6m_avg"] = (accounts_long["dpd_list"].apply(lambda x:np.mean(x[-6:])if len(x) > 0 else 0))

In [290]:
accounts_test_long["recent_6m_avg"] = (accounts_test_long["dpd_list"].apply(lambda x:np.mean(x[-6:])if len(x) > 0 else 0))

In [65]:
accounts_long[["recent_3m_avg", "recent_6m_avg"]].describe()

       recent_3m_avg  recent_6m_avg
count     1245310.00     1245310.00
mean            1.11           1.42
std            22.29          22.41
min             0.00           0.00
25%             0.00           0.00
50%             0.00           0.00
75%             0.00           0.00
max           969.00         924.00

In [66]:
#dpd_last wont be predicitve 
# dpd_max imp 
# ever_30_plus, ever_60_plus, ever_90_plus are imp features



### Account Features

In [67]:
account_features = pd.DataFrame()

account_features["num_loans"] = (accounts_long.groupby("uid").size())

In [291]:
account_test_features = pd.DataFrame()

account_test_features["num_loans"] = (accounts_test_long.groupby("uid").size())

In [68]:
account_features["num_active_loans"] = (accounts_long.groupby("uid")["is_active"].sum())

In [292]:
account_test_features["num_active_loans"] = (accounts_test_long.groupby("uid")["is_active"].sum())

In [69]:
account_features["num_closed_loans"] = (account_features["num_loans"] - account_features["num_active_loans"])

In [293]:
account_test_features["num_closed_loans"] = (account_test_features["num_loans"] - account_test_features["num_active_loans"])

In [70]:
account_features["active_loan_ratio"] = ( account_features["num_active_loans"] / account_features["num_loans"] )

In [294]:
account_test_features["active_loan_ratio"] = ( account_test_features["num_active_loans"] / account_test_features["num_loans"] )

In [298]:
loan_stats = (accounts_long.groupby("uid")["loan_amount"].agg([ "sum" ,"mean", "max","min", "std" , "median"]))

In [299]:
loan_test_stats = (accounts_test_long.groupby("uid")["loan_amount"].agg([ "sum" ,"mean", "max","min", "std" , "median"]))

In [72]:
loan_stats.columns = ["loan_sum","loan_mean","loan_max","loan_min","loan_std","loan_median"]

In [300]:
loan_test_stats.columns = ["loan_sum","loan_mean","loan_max","loan_min","loan_std","loan_median"]

In [73]:
account_features = ( account_features.join(loan_stats))

In [301]:
account_test_features = ( account_test_features.join(loan_test_stats))

In [74]:
accounts_long["has_overdue"] = (accounts_long["amount_overdue"] > 0).astype(int)

In [302]:
accounts_test_long["has_overdue"] = (accounts_test_long["amount_overdue"] > 0).astype(int)

In [75]:
overdue_stats = (accounts_long.groupby("uid").agg(
        overdue_sum=("amount_overdue","sum"),
        overdue_mean=("amount_overdue","mean"),
        overdue_max=("amount_overdue","max"),
        overdue_loans=("has_overdue","sum")
    )
)

In [303]:
overdue_test_stats = (accounts_test_long.groupby("uid").agg(
        overdue_sum=("amount_overdue","sum"),
        overdue_mean=("amount_overdue","mean"),
        overdue_max=("amount_overdue","max"),
        overdue_loans=("has_overdue","sum")
    )
)

In [76]:
account_features = ( account_features.join(overdue_stats))

In [304]:
account_test_features = ( account_test_features.join(overdue_test_stats))

In [77]:
account_features["overdue_loan_ratio"] = (account_features["overdue_loans"]/account_features["num_loans"])

In [305]:
account_test_features["overdue_loan_ratio"] = (account_test_features["overdue_loans"]/account_test_features["num_loans"])

In [78]:
credit_mix = (accounts_long.groupby("uid")["credit_type"].nunique())

In [306]:
credit_test_mix = (accounts_test_long.groupby("uid")["credit_type"].nunique())

In [79]:
account_features["num_credit_types"] = credit_mix

In [307]:
account_test_features["num_credit_types"] = credit_test_mix

In [80]:
# will improve this date feature further 
today = pd.Timestamp("2021-01-01")

In [81]:
accounts_long["loan_age_days"] = (today-accounts_long["open_date"]).dt.days

In [308]:
accounts_test_long["loan_age_days"] = (today-accounts_test_long["open_date"]).dt.days

In [82]:
age_features = (accounts_long.groupby("uid")["loan_age_days"].agg(["mean","max","min"]))

In [309]:
age_test_features = (accounts_test_long.groupby("uid")["loan_age_days"].agg(["mean","max","min"]))

In [83]:
age_features.columns = ["loan_age_mean","loan_age_max","loan_age_min"]

In [310]:
age_test_features.columns = ["loan_age_mean","loan_age_max","loan_age_min"]

In [84]:
account_features.shape

(223918, 16)

In [85]:
account_features.head()

,num_loans,num_active_loans,num_closed_loans,active_loan_ratio,loan_sum,loan_mean,loan_max,loan_min,loan_std,loan_median,overdue_sum,overdue_mean,overdue_max,overdue_loans,overdue_loan_ratio,num_credit_types
uid,,,,,,,,,,,,,,,,
AAA09044550,2,0,2,0.00,277245.00,138622.50,272745.00,4500.00,189677.86,138622.50,0.00,0.00,0.00,0,0.00,1
AAA10545297,1,1,0,1.00,80996.45,80996.45,80996.45,80996.45,NaN,80996.45,0.00,0.00,0.00,0,0.00,1
AAA14112888,1,0,1,0.00,43771.50,43771.50,43771.50,43771.50,NaN,43771.50,0.00,0.00,0.00,0,0.00,1
AAA20326915,8,3,5,0.38,591597.00,73949.62,235800.00,0.00,75716.66,46658.25,0.00,0.00,0.00,0,0.00,2
AAA31604840,5,3,2,0.60,1591960.50,318392.10,687150.00,41845.50,267948.77,304965.00,0.00,0.00,0.00,0,0.00,2

In [86]:
# DPD Features

In [87]:
dpd_features = pd.DataFrame()

In [311]:
dpd_test_features = pd.DataFrame()

In [88]:
#worst loan 
dpd_features["max_dpd_max"] = (accounts_long.groupby("uid")["dpd_max"].max())

In [312]:
dpd_test_features["max_dpd_max"] = (accounts_test_long.groupby("uid")["dpd_max"].max())

In [89]:
dpd_features["max_dpd_mean"] = (accounts_long.groupby("uid")["dpd_max"].mean())

In [313]:
dpd_test_features["max_dpd_mean"] = (accounts_test_long.groupby("uid")["dpd_max"].mean())

In [90]:
#recent behaviour
dpd_features["last_dpd_max"] = (accounts_long.groupby("uid")["dpd_last"].max())

In [314]:
dpd_test_features["last_dpd_max"] = (accounts_test_long.groupby("uid")["dpd_last"].max())

In [91]:
dpd_features["last_dpd_mean"] = (accounts_long.groupby("uid")["dpd_last"].mean())

In [315]:
dpd_test_features["last_dpd_mean"] = (accounts_test_long.groupby("uid")["dpd_last"].mean())

In [92]:
#Average delinquency
dpd_features["avg_dpd_mean"] = (accounts_long.groupby("uid")["dpd_avg"].mean())

In [316]:
dpd_test_features["avg_dpd_mean"] = (accounts_test_long.groupby("uid")["dpd_avg"].mean())

In [93]:
# worst delinquency

dpd_features["avg_dpd_max"] = (accounts_long.groupby("uid")["dpd_avg"].max())

In [317]:
dpd_test_features["avg_dpd_max"] = (accounts_test_long.groupby("uid")["dpd_avg"].max())

In [94]:
# Months Late
dpd_features["late_months_sum"] = (accounts_long.groupby("uid")["months_dpd_gt0"].sum())

In [318]:
dpd_test_features["late_months_sum"] = (accounts_test_long.groupby("uid")["months_dpd_gt0"].sum())

In [95]:
# Mean of late months
dpd_features["late_months_mean"] = (accounts_long.groupby("uid")["months_dpd_gt0"].mean())

In [319]:
dpd_test_features["late_months_mean"] = (accounts_test_long.groupby("uid")["months_dpd_gt0"].mean())

In [96]:
#30+ DPD months 
dpd_features["dpd30_sum"] = (accounts_long.groupby("uid")["months_dpd_gt30"].sum())

In [320]:
dpd_test_features["dpd30_sum"] = (accounts_test_long.groupby("uid")["months_dpd_gt30"].sum())

In [97]:
# 60+ DPD months
dpd_features["dpd60_sum"] = (accounts_long.groupby("uid")["months_dpd_gt60"].sum())

In [321]:
dpd_test_features["dpd60_sum"] = (accounts_test_long.groupby("uid")["months_dpd_gt60"].sum())

In [98]:
# 90+ DPD months
dpd_features["dpd90_sum"] = (accounts_long.groupby("uid")["months_dpd_gt90"].sum())

In [322]:
dpd_test_features["dpd90_sum"] = (accounts_test_long.groupby("uid")["months_dpd_gt90"].sum())

In [99]:
# 30+ DPD ever count
dpd_features["ever30_count"] = (accounts_long.groupby("uid")["ever_30_plus"].sum())

In [323]:
dpd_test_features["ever30_count"] = (accounts_test_long.groupby("uid")["ever_30_plus"].sum())

In [100]:
# 60+ DPD ever count
dpd_features["ever60_count"] = (accounts_long.groupby("uid")["ever_60_plus"].sum())

In [324]:
dpd_test_features["ever60_count"] = (accounts_test_long.groupby("uid")["ever_60_plus"].sum())

In [101]:
# 90+
dpd_features["ever90_count"] = (accounts_long.groupby("uid")["ever_90_plus"].sum())

In [325]:
dpd_test_features["ever90_count"] = (accounts_test_long.groupby("uid")["ever_90_plus"].sum())

In [102]:
# Sever Delinquency Count
dpd_features["ever90_ratio"] = (dpd_features["ever90_count"]/account_features["num_loans"])

In [326]:
dpd_test_features["ever90_ratio"] = (dpd_test_features["ever90_count"]/account_test_features["num_loans"])

In [103]:
dpd_features["trend_mean"] = (accounts_long.groupby("uid")["dpd_trend"].mean())

In [327]:
dpd_test_features["trend_mean"] = (accounts_test_long.groupby("uid")["dpd_trend"].mean())

In [104]:
# Worst Trend 
dpd_features["trend_max"] = (accounts_long.groupby("uid")["dpd_trend"].max())

In [328]:
dpd_test_features["trend_max"] = (accounts_test_long.groupby("uid")["dpd_trend"].max())

In [105]:
# Recent 3 month 
dpd_features["recent3_mean"] = (accounts_long.groupby("uid")["recent_3m_avg"].mean())

In [329]:
dpd_test_features["recent3_mean"] = (accounts_test_long.groupby("uid")["recent_3m_avg"].mean())

In [106]:
dpd_features["recent6_mean"] = (accounts_long.groupby("uid")["recent_6m_avg"].mean())

In [330]:
dpd_test_features["recent6_mean"] = (accounts_test_long.groupby("uid")["recent_6m_avg"].mean())

In [107]:
account_features = (account_features.join(dpd_features))

In [331]:
account_test_features = (account_test_features.join(dpd_test_features))

In [108]:
account_features.shape

(223918, 35)

In [332]:
account_test_features.shape

(39572, 35)

In [109]:
account_features.isnull().sum().sort_values(ascending=False).head(20)

loan_std              30704
loan_max                  1
loan_min                  1
loan_median               1
loan_mean                 1
num_loans                 0
num_active_loans          0
num_closed_loans          0
loan_sum                  0
active_loan_ratio         0
overdue_sum               0
overdue_mean              0
overdue_max               0
overdue_loans             0
overdue_loan_ratio        0
num_credit_types          0
max_dpd_max               0
max_dpd_mean              0
last_dpd_max              0
last_dpd_mean             0
dtype: int64

In [110]:
accounts_long["loan_amount"].isnull().sum()

np.int64(3)

In [111]:
accounts_long["loan_amount"] = (accounts_long["loan_amount"].fillna(0))

In [333]:
accounts_test_long["loan_amount"] = (accounts_test_long["loan_amount"].fillna(0))

In [112]:
account_features["loan_std"] = (account_features["loan_std"].fillna(0))

In [334]:
account_test_features["loan_std"] = (account_test_features["loan_std"].fillna(0))

In [113]:
#enquiry features

In [114]:
enquiry_features = pd.DataFrame()

In [335]:
enquiry_test_features = pd.DataFrame()

In [115]:
# Total Enquiries
enquiry_features["num_enquiries"] = (enquiry_long.groupby("uid").size())

In [336]:
enquiry_test_features["num_enquiries"] = (enquiry_test_long.groupby("uid").size())

In [116]:
# Unique enquiry types
enquiry_features["unique_enquiry_types"] = (enquiry_long.groupby("uid")["enquiry_type"].nunique())

In [337]:
enquiry_test_features["unique_enquiry_types"] = (enquiry_test_long.groupby("uid")["enquiry_type"].nunique())

In [117]:
# Enquiry Amount Statistics

amt_features = (enquiry_long.groupby("uid")["enquiry_amt"].agg([
        "sum",
        "mean",
        "max",
        "min",
        "std",
        "median"
    ])
)

In [338]:
# Enquiry Amount Statistics

amt_test_features = (enquiry_test_long.groupby("uid")["enquiry_amt"].agg([
        "sum",
        "mean",
        "max",
        "min",
        "std",
        "median"
    ])
)

In [118]:
amt_features.columns = ["enq_amt_sum","enq_amt_mean","enq_amt_max","enq_amt_min","enq_amt_std","enq_amt_median"]

In [339]:
amt_test_features.columns = ["enq_amt_sum","enq_amt_mean","enq_amt_max","enq_amt_min","enq_amt_std","enq_amt_median"]

In [119]:
enquiry_features = (enquiry_features.join(amt_features))

In [340]:
enquiry_test_features = (enquiry_test_features.join(amt_test_features))

In [120]:
enquiry_type_counts = (pd.crosstab(enquiry_long["uid"],enquiry_long["enquiry_type"]))

In [341]:
enquiry_test_type_counts = (pd.crosstab(enquiry_test_long["uid"],enquiry_test_long["enquiry_type"]))

In [121]:
enquiry_features = (enquiry_features.join(enquiry_type_counts))

In [342]:
enquiry_test_features = (enquiry_test_features.join(enquiry_test_type_counts))

In [122]:
reference_date = (enquiry_long["enquiry_date"].max())

In [344]:
reference_test_date = (enquiry_test_long["enquiry_date"].max())

In [123]:
enquiry_long["days_since_enquiry"] = (reference_date - enquiry_long["enquiry_date"]).dt.days

In [345]:
enquiry_test_long["days_since_enquiry"] = (reference_test_date - enquiry_test_long["enquiry_date"]).dt.days

In [124]:
recency = (enquiry_long.groupby("uid")["days_since_enquiry"].agg(["min","mean","max"]))

In [346]:
recency_test = (enquiry_test_long.groupby("uid")["days_since_enquiry"].agg(["min","mean","max"]))

In [125]:
recency.columns = ["last_enquiry_days","avg_enquiry_days","oldest_enquiry_days"]

In [347]:
recency_test.columns = ["last_enquiry_days","avg_enquiry_days","oldest_enquiry_days"]

In [126]:
enquiry_features = (enquiry_features.join(recency))

In [348]:
enquiry_test_features = (enquiry_test_features.join(recency_test))

In [127]:
enquiry_features["enquiries_30d"] = (enquiry_long[enquiry_long["days_since_enquiry"] <= 30].groupby("uid").size())

In [349]:
enquiry_test_features["enquiries_30d"] = (enquiry_test_long[enquiry_test_long["days_since_enquiry"] <= 30].groupby("uid").size())

In [128]:
enquiry_features["enquiries_90d"] = (enquiry_long[enquiry_long["days_since_enquiry"] <= 90].groupby("uid").size())

In [350]:
enquiry_test_features["enquiries_90d"] = (enquiry_test_long[enquiry_test_long["days_since_enquiry"] <= 90].groupby("uid").size())

In [129]:
enquiry_features["enquiries_180d"] = (enquiry_long[enquiry_long["days_since_enquiry"] <= 180].groupby("uid").size())

In [351]:
enquiry_test_features["enquiries_180d"] = (enquiry_test_long[enquiry_test_long["days_since_enquiry"] <= 180].groupby("uid").size())

In [130]:
enquiry_features[["enquiries_30d","enquiries_90d","enquiries_180d"]] = (enquiry_features[["enquiries_30d","enquiries_90d","enquiries_180d"] ].fillna(0))

In [352]:
enquiry_test_features[["enquiries_30d","enquiries_90d","enquiries_180d"]] = (enquiry_test_features[["enquiries_30d","enquiries_90d","enquiries_180d"] ].fillna(0))

In [131]:
master_features = (account_features.join(enquiry_features))

In [353]:
master_test_features = (account_test_features.join(enquiry_test_features))

In [132]:
master_features.shape

(223918, 66)

In [354]:
master_test_features.shape

(39572, 66)

In [133]:
master_features.head()

,num_loans,num_active_loans,num_closed_loans,active_loan_ratio,loan_sum,loan_mean,loan_max,loan_min,loan_std,loan_median,overdue_sum,overdue_mean,overdue_max,overdue_loans,overdue_loan_ratio,num_credit_types,max_dpd_max,max_dpd_mean,last_dpd_max,last_dpd_mean,avg_dpd_mean,avg_dpd_max,late_months_sum,late_months_mean,dpd30_sum,dpd60_sum,dpd90_sum,ever30_count,ever60_count,ever90_count,ever90_ratio,trend_mean,trend_max,recent3_mean,recent6_mean,num_enquiries,unique_enquiry_types,enq_amt_sum,enq_amt_mean,enq_amt_max,enq_amt_min,enq_amt_std,enq_amt_median,Another type of loan,Car loan,Cash loan (non-earmarked),Cash loans,Consumer credit,Credit card,Interbank credit,Loan for business development,Loan for purchase of shares (margin lending),Loan for the purchase of equipment,Loan for working capital replenishment,Microloan,Mobile operator loan,Mortgage,Real estate loan,Revolving loans,Unknown type of loan,last_enquiry_days,avg_enquiry_days,oldest_enquiry_days,enquiries_30d,enquiries_90d,enquiries_180d
uid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
AAA09044550,2,0,2,0.00,277245.00,138622.50,272745.00,4500.00,189677.86,138622.50,0.00,0.00,0.00,0,0.00,1,44,27.00,0,0.00,2.11,3.62,3,1.50,1,0,0,1,0,0,0.00,0.00,0,0.00,0.00,26,14,2659000,102269.23,197000,5000,50263.75,106500.00,3,3,1,7,1,1,2,0,0,1,0,2,1,1,1,1,1,3,289.54,1172,3.00,7.00,10.00
AAA10545297,1,1,0,1.00,80996.45,80996.45,80996.45,80996.45,0.00,80996.45,0.00,0.00,0.00,0,0.00,1,0,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0.00,0.00,0,0.00,0.00,14,9,1317000,94071.43,192000,5000,66014.53,94000.00,1,0,2,2,2,2,1,0,1,0,0,0,0,0,0,2,1,64,359.14,910,0.00,1.00,4.00
AAA14112888,1,0,1,0.00,43771.50,43771.50,43771.50,43771.50,0.00,43771.50,0.00,0.00,0.00,0,0.00,1,0,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0.00,0.00,0,0.00,0.00,15,10,1465000,97666.67,185000,17000,49185.75,95000.00,1,0,1,1,2,0,1,0,2,2,2,0,2,0,0,0,1,180,462.40,1359,0.00,0.00,1.00
AAA20326915,8,3,5,0.38,591597.00,73949.62,235800.00,0.00,75716.66,46658.25,0.00,0.00,0.00,0,0.00,2,917,114.62,0,0.00,23.81,190.49,31,3.88,30,29,28,1,1,1,0.12,0.00,0,0.00,37.58,1,1,66000,66000.00,66000,66000,NaN,66000.00,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,140,140.00,140,0.00,0.00,1.00
AAA31604840,5,3,2,0.60,1591960.50,318392.10,687150.00,41845.50,267948.77,304965.00,0.00,0.00,0.00,0,0.00,2,0,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0.00,0.00,0,0.00,0.00,19,10,1826000,96105.26,195000,10000,60127.54,80000.00,1,0,1,1,2,0,1,3,2,2,0,0,0,0,2,0,4,35,335.95,860,0.00,4.00,8.00

In [134]:
master_features.isnull().sum().sort_values(ascending=False).head(20)

enq_amt_std           48085
loan_mean                 1
loan_max                  1
loan_median               1
loan_min                  1
num_loans                 0
num_active_loans          0
loan_sum                  0
num_closed_loans          0
active_loan_ratio         0
overdue_sum               0
overdue_mean              0
overdue_max               0
overdue_loans             0
overdue_loan_ratio        0
num_credit_types          0
max_dpd_max               0
loan_std                  0
last_dpd_max              0
last_dpd_mean             0
dtype: int64

In [135]:
master_features["loan_mean"] = master_features["loan_mean"].fillna(0)
master_features["loan_max"] = master_features["loan_max"].fillna(0)
master_features["loan_min"] = master_features["loan_min"].fillna(0)
master_features["loan_median"] = master_features["loan_median"].fillna(0)

master_features["enq_amt_std"] = (master_features["enq_amt_std"].fillna(0))

In [355]:
master_test_features["loan_mean"] = master_test_features["loan_mean"].fillna(0)
master_test_features["loan_max"] = master_test_features["loan_max"].fillna(0)
master_test_features["loan_min"] = master_test_features["loan_min"].fillna(0)
master_test_features["loan_median"] = master_test_features["loan_median"].fillna(0)

master_test_features["enq_amt_std"] = (master_test_features["enq_amt_std"].fillna(0))

In [136]:
# Loan Tenure Feature
accounts_long["loan_tenure_days"] = (accounts_long["closed_date"]-accounts_long["open_date"]).dt.days

In [356]:
# Loan Tenure Feature
accounts_test_long["loan_tenure_days"] = (accounts_test_long["closed_date"]-accounts_test_long["open_date"]).dt.days

In [137]:
# Active Loans 
accounts_long["loan_tenure_days"] = (accounts_long["loan_tenure_days"].fillna((pd.Timestamp("2021-01-01")-accounts_long["open_date"]).dt.days))

In [357]:
accounts_test_long["loan_tenure_days"] = (accounts_test_long["loan_tenure_days"].fillna((pd.Timestamp("2021-01-01")-accounts_test_long["open_date"]).dt.days))

In [138]:
tenure_features = (accounts_long.groupby("uid")["loan_tenure_days"].agg(["mean","max","min","std","median"]))

In [358]:
tenure_test_features = (accounts_test_long.groupby("uid")["loan_tenure_days"].agg(["mean","max","min","std","median"]))

In [139]:
tenure_features.columns = ["tenure_mean","tenure_max","tenure_min", "tenure_std","tenure_median"]

In [359]:
tenure_test_features.columns = ["tenure_mean","tenure_max","tenure_min", "tenure_std","tenure_median"]

In [140]:
master_features = (master_features.join(tenure_features))

In [360]:
master_test_features = (master_test_features.join(tenure_test_features))

In [141]:
credit_counts = pd.crosstab(accounts_long["uid"],accounts_long["credit_type"])

In [361]:
credit_test_counts = pd.crosstab(accounts_test_long["uid"],accounts_test_long["credit_type"])

In [142]:
# Normalized Credit Type Ratios
credit_ratios = (credit_counts.div(credit_counts.sum(axis=1),axis=0))

In [362]:
credit_test_ratios = (credit_test_counts.div(credit_test_counts.sum(axis=1),axis=0))

In [143]:
credit_ratios.columns = [f"ratio_{c}" for c in credit_ratios.columns]

In [363]:
credit_test_ratios.columns = [f"ratio_{c}" for c in credit_test_ratios.columns]

In [144]:
master_features = (master_features.join(credit_ratios))

In [364]:
master_test_features = (master_test_features.join(credit_test_ratios))

In [145]:
master_features["dominant_credit_ratio"] = (credit_ratios.max(axis=1))

In [365]:
master_test_features["dominant_credit_ratio"] = (credit_test_ratios.max(axis=1))

In [146]:
master_features["enquiries_per_loan"] = (master_features["num_enquiries"]/master_features["num_loans"])

In [366]:
master_test_features["enquiries_per_loan"] = (master_test_features["num_enquiries"]/master_test_features["num_loans"])

In [147]:
master_features["overdue_per_loan"] = (master_features["overdue_sum"]/( master_features["num_loans"] + 1))

In [367]:
master_test_features["overdue_per_loan"] = (master_test_features["overdue_sum"]/( master_test_features["num_loans"] + 1))

In [148]:
master_features["active_to_closed_ratio"] = (master_features["num_active_loans"]/(master_features["num_closed_loans"]+ 1))

In [368]:
master_test_features["active_to_closed_ratio"] = (master_test_features["num_active_loans"]/(master_test_features["num_closed_loans"]+ 1))

In [149]:
master_features["dpd90_per_loan"] = (master_features["dpd90_sum"]/( master_features["num_loans"]+ 1))

In [369]:
master_test_features["dpd90_per_loan"] = (master_test_features["dpd90_sum"]/( master_test_features["num_loans"]+ 1))

In [150]:
master_features["chronic_delinquency"] = (master_features["late_months_sum"]/(master_features["num_loans"]+ 1))

In [370]:
master_test_features["chronic_delinquency"] = (master_test_features["late_months_sum"]/(master_test_features["num_loans"]+ 1))

In [151]:
master_features["dpd_severity"] = (master_features["max_dpd_mean"]*master_features["late_months_mean"])

In [371]:
master_test_features["dpd_severity"] = (master_test_features["max_dpd_mean"]*master_test_features["late_months_mean"])

In [152]:
master_features["enquiry_velocity_30"] = (master_features["enquiries_30d"]/( master_features["num_enquiries"] + 1))

In [372]:
master_test_features["enquiry_velocity_30"] = (master_test_features["enquiries_30d"]/( master_test_features["num_enquiries"] + 1))

In [153]:
master_features["enquiry_velocity_90"] = (master_features["enquiries_90d"]/( master_features["num_enquiries"]+ 1))

In [403]:
master_test_features["enquiry_velocity_90"] = (master_test_features["enquiries_90d"]/( master_test_features["num_enquiries"] + 1))

In [154]:
master_features["enquiry_velocity_180"] = (master_features["enquiries_180d"]/( master_features["num_enquiries"] + 1))

In [374]:
master_test_features["enquiry_velocity_180"] = (master_test_features["enquiries_180d"]/( master_test_features["num_enquiries"] + 1))

In [155]:
master_features.shape

(223918, 96)

In [402]:
master_test_features.shape

(39572, 103)

In [156]:
master_features.isnull().sum().sort_values(ascending=False).head(20)

tenure_std            30704
num_loans                 0
num_closed_loans          0
num_active_loans          0
loan_sum                  0
loan_mean                 0
loan_max                  0
active_loan_ratio         0
loan_std                  0
loan_median               0
overdue_sum               0
overdue_mean              0
overdue_max               0
overdue_loans             0
overdue_loan_ratio        0
loan_min                  0
max_dpd_max               0
max_dpd_mean              0
last_dpd_max              0
last_dpd_mean             0
dtype: int64

In [157]:
master_features.isnull().sum().sum()

np.int64(30704)

In [158]:
master_features["tenure_std"] = (master_features["tenure_std"].fillna(0))

In [377]:
master_test_features["tenure_std"] = (master_test_features["tenure_std"].fillna(0))

In [159]:
master_features.isnull().sum().sum()

np.int64(0)

In [160]:
master_features["has_credit_history"] = 1

In [378]:
master_test_features["has_credit_history"] = 1

In [161]:
# Credit Utlization Ratio
master_features["overdue_to_loan_ratio"] = (master_features["overdue_sum"]/(master_features["loan_sum"] + 1))

In [379]:
master_test_features["overdue_to_loan_ratio"] = (master_test_features["overdue_sum"]/(master_test_features["loan_sum"] + 1))

In [162]:
master_features["ever90_density"] = (master_features["ever90_count"]/(master_features["num_loans"] + 1))

In [380]:
master_test_features["ever90_density"] = (master_test_features["ever90_count"]/(master_test_features["num_loans"] + 1))

In [163]:
master_features["ever60_density"] = (master_features["ever60_count"]/(master_features["num_loans"] + 1))

In [381]:
master_test_features["ever60_density"] = (master_test_features["ever60_count"]/(master_test_features["num_loans"] + 1))

In [164]:
master_features["ever30_density"] = (master_features["ever30_count"]/(master_features["num_loans"] + 1))

In [382]:
master_test_features["ever30_density"] = (master_test_features["ever30_count"]/(master_test_features["num_loans"] + 1))

In [165]:
# Loan amount concentrate 
master_features["loan_concentration"] = (master_features["loan_max"]/(master_features["loan_sum"] + 1))

In [383]:
master_test_features["loan_concentration"] = (master_test_features["loan_max"]/(master_test_features["loan_sum"] + 1))

In [166]:
master_features["enquiry_amount_per_loan"] = (master_features["enq_amt_sum"]/(master_features["num_loans"] + 1))

In [384]:
master_test_features["enquiry_amount_per_loan"] = (master_test_features["enq_amt_sum"]/(master_test_features["num_loans"] + 1))

In [167]:
master_features["active_exposure"] = (master_features["active_loan_ratio"]*master_features["loan_sum"])

In [385]:
master_test_features["active_exposure"] = (master_test_features["active_loan_ratio"]*master_test_features["loan_sum"])

In [168]:
master_features["worst_account_score"] = (master_features["max_dpd_max"]*master_features["ever90_count"])

In [386]:
master_test_features["worst_account_score"] = (master_test_features["max_dpd_max"]*master_test_features["ever90_count"])

In [169]:
master_features["recent_risk_score"] = (master_features["recent3_mean"]+ master_features["recent6_mean"])

In [387]:
master_test_features["recent_risk_score"] = (master_test_features["recent3_mean"]+ master_test_features["recent6_mean"])

In [170]:
train_df = train_flag.merge(master_features,on="uid",how="left")

In [171]:
train_df.shape

(261383, 109)

In [172]:
train_df["has_credit_history"] = (train_df["num_loans"].notna().astype(int))

In [173]:
feature_cols = [
    c for c in train_df.columns
    if c not in ["uid", "TARGET"]
]

train_df[feature_cols] = (train_df[feature_cols].fillna(0))

In [174]:
train_df.isnull().sum().sum()

np.int64(0)

In [432]:
test_raw_df = test_flag.merge( master_test_features,on="uid",how="left")

In [405]:
test_raw_df["has_credit_history"] = (test_raw_df["num_loans"].notna().astype(int))

In [406]:
feature_cols = [
    c for c in test_raw_df.columns
    if c not in ["uid","TARGET"]
]

test_raw_df[feature_cols] = (test_raw_df[feature_cols].fillna(0))

In [407]:
print(test_raw_df.shape)
print(test_raw_df.isnull().sum().sum())

(46127, 105)
0

In [448]:
train_features = set(train_df.columns) - {"uid", "TARGET"}
test_features = set(test_raw_df.columns) - {"uid"}


print("Missing in test:")
print(sorted(train_features - test_features))

print("\nExtra in test:")
print(sorted(test_features - train_features))

Missing in test:
[]

Extra in test:
[]

In [454]:
train_feature_cols = [c for c in train_df.columns if c not in ["uid", "TARGET"]]

# Add missing columns to test
for col in train_feature_cols:
    if col not in test_raw_df.columns:
        test_raw_df[col] = 0

extra_cols = [
    c for c in test_raw_df.columns
    if c not in train_df.columns and c != "uid"
]

test_raw_df.drop(columns=extra_cols, inplace=True)

test_raw_df = test_raw_df[["uid"] + train_feature_cols]

In [455]:
test_raw_df.shape

(46127, 120)

In [456]:
train_df.shape

(261383, 121)

In [394]:
constant_features = [c for c in feature_cols if train_df[c].nunique() <= 1]

len(constant_features)

1

In [395]:
train_df.drop(columns=constant_features,inplace=True)

test_raw_df.drop(columns=constant_features,inplace=True)

In [ ]:
# corr_matrix = (train_df[feature_cols].corr().abs())

ValueError: could not convert string to float: 'Cash loans'

In [182]:
train_df.select_dtypes(include=["object"]).columns.tolist()

['uid', 'NAME_CONTRACT_TYPE']

In [183]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 261383 entries, 0 to 261382
Columns: 109 entries, uid to recent_risk_score
dtypes: float64(105), int64(2), str(2)
memory usage: 222.7 MB

In [184]:
train_df["NAME_CONTRACT_TYPE"].value_counts(dropna=False)

NAME_CONTRACT_TYPE
Cash loans         236524
Revolving loans     24859
Name: count, dtype: int64

In [421]:
test_raw_df["NAME_CONTRACT_TYPE"].value_counts(dropna=False)

NAME_CONTRACT_TYPE
Cash loans         41707
Revolving loans     4420
Name: count, dtype: int64

In [185]:
# Cash loans - 0, Revolving loans - 1

In [439]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

train_df["NAME_CONTRACT_TYPE"] = le.fit_transform( train_df["NAME_CONTRACT_TYPE"])
test_raw_df["NAME_CONTRACT_TYPE"] = le.fit_transform(test_raw_df["NAME_CONTRACT_TYPE"])

In [217]:
X = train_df.drop(columns=["uid", "TARGET"])

print(X.shape)
print(X.dtypes.value_counts())

(261383, 120)
float64    118
int64        2
Name: count, dtype: int64

In [188]:
corr_matrix = X.corr().abs()

upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(bool))

high_corr = [
    col
    for col in upper.columns
    if any(upper[col] > 0.98)
]

print(len(high_corr))
print(high_corr[:20])

8
['late_months_mean', 'dpd30_sum', 'dpd60_sum', 'dpd90_sum', 'trend_mean', 'trend_max', 'enq_amt_median', 'recent_risk_score']

In [190]:
y = train_df["TARGET"]

In [191]:
scale_pos_weight = ((y == 0).sum()/(y == 1).sum())

print(scale_pos_weight)

11.41311677826851

In [ ]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import lightgbm as lgb

In [193]:
kf = StratifiedKFold(n_splits=5,shuffle=True, random_state=42)

In [194]:
oof = np.zeros(len(X))
scores = []

In [195]:
for fold, (train_idx,valid_idx) in enumerate(kf.split(X,y)):

    X_train = X.iloc[train_idx]
    X_valid = X.iloc[valid_idx]
    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = lgb.LGBMClassifier(n_estimators=1000,learning_rate=0.03,num_leaves=63,subsample=0.8,colsample_bytree=0.8,random_state=42,n_jobs=-1,scale_pos_weight=scale_pos_weight)

    model.fit(X_train,y_train)
    pred = model.predict_proba(X_valid)[:,1]
    score = roc_auc_score(y_valid,pred)

    print(f"Fold {fold+1}: {score:.5f}")
    scores.append(score)
    oof[valid_idx] = pred

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16846, number of negative: 192260
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.074309 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13923
[LightGBM] [Info] Number of data points in the train set: 209106, number of used features: 101
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080562 -> initscore=-2.434735
[LightGBM] [Info] Start training from score -2.434735
Fold 1: 0.65670
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16845, number of negative: 192261
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.108087 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13938
[LightGBM] [Info] Number of data points in the train set: 209106, number of used features: 101
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080557 -> initscore=-2.434800
[LightGBM] [Info] Start training from score -2.434800
Fold 2: 0.65372
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16845, number of negative: 192261
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.106846 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13946
[LightGBM] [Info] Number of data points in the train set: 209106, number of used features: 101
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080557 -> initscore=-2.434800
[LightGBM] [Info] Start training from score -2.434800
Fold 3: 0.65661
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16846, number of negative: 192261
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.108805 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13934
[LightGBM] [Info] Number of data points in the train set: 209107, number of used features: 101
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080562 -> initscore=-2.434741
[LightGBM] [Info] Start training from score -2.434741
Fold 4: 0.65856
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16846, number of negative: 192261
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.073535 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13968
[LightGBM] [Info] Number of data points in the train set: 209107, number of used features: 101
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080562 -> initscore=-2.434741
[LightGBM] [Info] Start training from score -2.434741
Fold 5: 0.65332

In [196]:
print("CV AUC:" , np.mean(scores))

CV AUC: 0.6557833042562826

In [197]:
importance = pd.DataFrame({"feature": X.columns,"importance": model.feature_importances_})

In [198]:
importance = (importance.sort_values("importance",ascending=False))

In [199]:
importance.head(20)
#dpd features are not that dominating

                 feature  importance
62      avg_enquiry_days        2492
69            tenure_min        2330
63   oldest_enquiry_days        2276
102   loan_concentration        2121
71         tenure_median        1889
8               loan_min        1888
10           loan_median        1859
41           enq_amt_min        1805
68            tenure_max        1801
61     last_enquiry_days        1777
43        enq_amt_median        1712
67           tenure_mean        1705
42           enq_amt_std        1674
40           enq_amt_max        1653
39          enq_amt_mean        1627
70            tenure_std        1543
7               loan_max        1476
104      active_exposure        1472
38           enq_amt_sum        1444
6              loan_mean        1434

In [200]:
# Retraining to get the feature importance of the dpd

In [202]:
def recent12_max(x):
    if len(x) == 0:
        return 0
    return max(x[-12:])

def recent6_max(x):
    if len(x) == 0:
        return 0
    return max(x[-6:])

def recent3_max(x):
    if len(x) == 0:
        return 0
    return max(x[-3:])

def weighted_dpd(x):
    if len(x) == 0:
        return 0

    weights = np.arange(1, len(x)+1)

    return np.average(x,weights=weights)

def delinquency_ratio(x):
    if len(x) == 0:
        return 0

    return (sum(v > 0 for v in x)/ len(x))

def longest_streak(x):

    best = 0
    cur = 0

    for v in x:

        if v > 0:
            cur += 1
            best = max(best, cur)
        else:
            cur = 0

    return best

def dpd_volatility(x):

    if len(x) <= 1:
        return 0

    return np.std(x)

def recovery_score(x):

    if len(x) < 2:
        return 0

    return x[0] - x[-1]

In [203]:
accounts_long["recent12_max_dpd"] = (accounts_long["dpd_list"].apply(recent12_max))
accounts_long["recent6_max_dpd"] = (accounts_long["dpd_list"].apply(recent6_max))
accounts_long["recent3_max_dpd"] = (accounts_long["dpd_list"].apply(recent3_max))
accounts_long["weighted_dpd"] = (accounts_long["dpd_list"].apply(weighted_dpd))
accounts_long["delinquency_ratio"] = (accounts_long["dpd_list"].apply(delinquency_ratio))
accounts_long["longest_delinquency_streak"] = (accounts_long["dpd_list"].apply(longest_streak))
accounts_long["dpd_volatility"] = (accounts_long["dpd_list"].apply(dpd_volatility))
accounts_long["recovery_score"] = (accounts_long["dpd_list"].apply(recovery_score))

In [204]:
dpd_v2 = (accounts_long.groupby("uid").agg(
        recent12_max_dpd_max = ("recent12_max_dpd","max"),
        recent6_max_dpd_max = ("recent6_max_dpd","max"),
        recent3_max_dpd_max = ("recent3_max_dpd","max"),
        weighted_dpd_mean = ("weighted_dpd","mean"),
        weighted_dpd_max = ("weighted_dpd","max"),
        delinquency_ratio_mean = ("delinquency_ratio","mean"),
        delinquency_ratio_max = ("delinquency_ratio","max"),
        longest_streak_max = ("longest_delinquency_streak","max"),
        longest_streak_mean = ("longest_delinquency_streak","mean"),
        dpd_volatility_mean = ("dpd_volatility","mean"),
        dpd_volatility_max = ( "dpd_volatility","max"),
        recovery_score_mean = ("recovery_score","mean"),
        recovery_score_max = ("recovery_score","max" )
    )
)

In [205]:
master_features = (master_features.join(dpd_v2))

In [206]:
print(master_features.shape)

(223918, 119)

In [207]:
master_features[["recent12_max_dpd_max","weighted_dpd_mean","delinquency_ratio_mean","longest_streak_max","dpd_volatility_mean","recovery_score_mean"]].describe()

,recent12_max_dpd_max,weighted_dpd_mean,delinquency_ratio_mean,longest_streak_max,dpd_volatility_mean,recovery_score_mean
count,223918.00,223918.00,223918.00,223918.00,223918.00,223918.00
mean,24.21,1.43,0.02,1.34,2.05,-0.58
std,81.57,9.09,0.04,3.46,7.92,14.28
min,0.00,0.00,0.00,0.00,0.00,-999.00
25%,0.00,0.00,0.00,0.00,0.00,0.00
50%,0.00,0.00,0.00,0.00,0.00,0.00
75%,9.00,0.29,0.02,1.00,1.12,0.00
max,999.00,669.00,1.00,81.00,325.60,25.00

In [ ]:
train_df = train_flag.merge(master_features,on="uid",how="left")
# test_df = test_flag.merge(master_features,on="uid",how="left" )

In [ ]:
train_df["has_credit_history"] = (train_df["num_loans"].notna().astype(int))
# test_df["has_credit_history"] = (test_df["num_loans"].notna().astype(int))

In [ ]:
feature_cols = [ c for c in train_df.columns if c not in ["uid", "TARGET"]]

train_df[feature_cols] = (train_df[feature_cols].fillna(0))
# test_df[feature_cols] = (test_df[feature_cols].fillna(0))

In [211]:
X = train_df.drop( columns=["uid", "TARGET"])
y = train_df["TARGET"]

In [ ]:
scale_pos_weight = ((y == 0).sum()/(y == 1).sum())
print(scale_pos_weight)

11.41311677826851

In [213]:
kf = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

oof = np.zeros(len(X))
scores = []
feature_importances = []

In [218]:
for fold, (train_idx, valid_idx) in enumerate(kf.split(X, y)):

    X_train = X.iloc[train_idx]
    X_valid = X.iloc[valid_idx]
    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = lgb.LGBMClassifier(objective="binary",n_estimators=3000,learning_rate=0.02,num_leaves=63,subsample=0.8,colsample_bytree=0.8,scale_pos_weight=scale_pos_weight,random_state=42,n_jobs=-1)

    model.fit(X_train,y_train,eval_set=[(X_valid, y_valid)],callbacks=[lgb.early_stopping(100,verbose=False)])

    pred = model.predict_proba(X_valid)[:, 1]
    oof[valid_idx] = pred
    score = roc_auc_score(y_valid,pred)

    print(f"Fold {fold+1}: {score:.5f}")

    scores.append(score)
    feature_importances.append(model.feature_importances_)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16846, number of negative: 192260
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.119411 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 16761
[LightGBM] [Info] Number of data points in the train set: 209106, number of used features: 114
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080562 -> initscore=-2.434735
[LightGBM] [Info] Start training from score -2.434735
Fold 1: 0.63215
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16845, number of negative: 192261
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.054344 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16778
[LightGBM] [Info] Number of data points in the train set: 209106, number of used features: 114
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080557 -> initscore=-2.434800
[LightGBM] [Info] Start training from score -2.434800
Fold 2: 0.63864
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16845, number of negative: 192261
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.091136 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 16789
[LightGBM] [Info] Number of data points in the train set: 209106, number of used features: 114
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080557 -> initscore=-2.434800
[LightGBM] [Info] Start training from score -2.434800
Fold 3: 0.63127
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16846, number of negative: 192261
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.078127 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16776
[LightGBM] [Info] Number of data points in the train set: 209107, number of used features: 114
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080562 -> initscore=-2.434741
[LightGBM] [Info] Start training from score -2.434741
Fold 4: 0.63852
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 16846, number of negative: 192261
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.148256 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 16813
[LightGBM] [Info] Number of data points in the train set: 209107, number of used features: 114
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080562 -> initscore=-2.434741
[LightGBM] [Info] Start training from score -2.434741
Fold 5: 0.62684

In [219]:
print("\nMean CV:",np.mean(scores))
print("OOF AUC:",roc_auc_score(y,oof))

Mean CV: 0.6334840250795389
OOF AUC: 0.6335187536739302

In [220]:
importance = pd.DataFrame({"feature": X.columns,"importance": np.mean(feature_importances,axis=0)})
importance = (importance.sort_values( "importance",ascending=False))

importance.head(30)

                    feature  importance
63      oldest_enquiry_days        9.20
67              tenure_mean        8.00
90   active_to_closed_ratio        8.00
69               tenure_min        3.60
96     enquiry_velocity_180        3.60
40              enq_amt_max        3.40
6                 loan_mean        3.00
38              enq_amt_sum        2.80
2          num_active_loans        2.80
5                  loan_sum        2.40
4         active_loan_ratio        2.00
82          ratio_Microloan        1.80
7                  loan_max        1.60
66           enquiries_180d        1.60
65            enquiries_90d        1.20
11              overdue_sum        0.80
61        last_enquiry_days        0.60
73           ratio_Car loan        0.60
3          num_closed_loans        0.40
39             enq_amt_mean        0.40
70               tenure_std        0.40
68               tenure_max        0.40
1                 num_loans        0.40
95      enquiry_velocity_90        0.40
98    overdue_to_loan_ratio        0.40
102      loan_concentration        0.20
92      chronic_delinquency        0.20
15       overdue_loan_ratio        0.20
36            num_enquiries        0.20
12             overdue_mean        0.20

In [224]:
# Even new features are not that dominating and degrading the performance. Hence we will stick to the previous features only and ignore these new dpd features.

In [424]:
train_df_base = train_df.drop(columns=dpd_v2,errors="ignore")
test_df_base = test_raw_df.drop(columns=dpd_v2,errors="ignore")

In [440]:
train_df_base.shape

(261383, 108)

In [441]:
test_df_base.shape

(46127, 107)

In [228]:
from catboost import CatBoostClassifier

In [229]:
X = train_df_base.drop(columns=["uid", "TARGET"])
y = train_df_base["TARGET"]

In [230]:
kf = StratifiedKFold( n_splits=5,shuffle=True,random_state=42)

scores = []
oof = np.zeros(len(X))
feature_importances = []

In [231]:
for fold, (train_idx, valid_idx) in enumerate(kf.split(X, y)):

    X_train = X.iloc[train_idx]
    X_valid = X.iloc[valid_idx]
    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = CatBoostClassifier(
        iterations=5000,
        learning_rate=0.03,
        depth=6,
        loss_function="Logloss",
        eval_metric="AUC",
        random_seed=42,
        verbose=False
    )

    model.fit(X_train,y_train, eval_set=(X_valid,y_valid),use_best_model=True)
    pred = model.predict_proba(X_valid)[:,1]
    score = roc_auc_score( y_valid, pred)

    print(f"Fold {fold+1}: {score:.5f}")

    scores.append(score)
    oof[valid_idx] = pred
    feature_importances.append(model.feature_importances_)

Fold 1: 0.67659
Fold 2: 0.67348
Fold 3: 0.67468
Fold 4: 0.67689
Fold 5: 0.67094

In [232]:
print("Mean CV:",np.mean(scores))
print("Std Dev:",np.std(scores))
print("OOF AUC:",roc_auc_score(y,oof))

Mean CV: 0.6745169128866859
Std Dev: 0.0021820198702595535
OOF AUC: 0.6742032550480157

In [233]:
importance = pd.DataFrame({"feature": X.columns,"importance": np.mean(feature_importances,axis=0)})

In [234]:
importance = (importance.sort_values("importance",ascending=False))

importance.head(20)

                    feature  importance
62         avg_enquiry_days       14.93
90   active_to_closed_ratio        6.58
4         active_loan_ratio        5.70
63      oldest_enquiry_days        5.32
67              tenure_mean        4.80
69               tenure_min        3.60
71            tenure_median        3.46
2          num_active_loans        2.92
0        NAME_CONTRACT_TYPE        2.77
8                  loan_min        2.43
10              loan_median        2.36
7                  loan_max        2.00
96     enquiry_velocity_180        1.91
6                 loan_mean        1.82
68               tenure_max        1.64
104         active_exposure        1.48
36            num_enquiries        1.47
38              enq_amt_sum        1.46
102      loan_concentration        1.38
70               tenure_std        1.37

In [235]:
final_cat = CatBoostClassifier(iterations=5000,learning_rate=0.03,depth=6,loss_function="Logloss",eval_metric="AUC",random_seed=42,verbose=200)

In [236]:
final_cat.fit(X,y)

0:	total: 174ms	remaining: 14m 31s
200:	total: 20.9s	remaining: 8m 19s
400:	total: 40.3s	remaining: 7m 41s
600:	total: 56.6s	remaining: 6m 54s
800:	total: 1m 13s	remaining: 6m 25s
1000:	total: 1m 31s	remaining: 6m 3s
1200:	total: 1m 48s	remaining: 5m 43s
1400:	total: 2m 5s	remaining: 5m 21s
1600:	total: 2m 22s	remaining: 5m 2s
1800:	total: 2m 38s	remaining: 4m 41s
2000:	total: 2m 56s	remaining: 4m 25s
2200:	total: 3m 14s	remaining: 4m 7s
2400:	total: 3m 31s	remaining: 3m 48s
2600:	total: 3m 48s	remaining: 3m 30s
2800:	total: 4m 4s	remaining: 3m 11s
3000:	total: 4m 21s	remaining: 2m 54s
3200:	total: 4m 37s	remaining: 2m 36s
3400:	total: 4m 54s	remaining: 2m 18s
3600:	total: 5m 10s	remaining: 2m
3800:	total: 5m 26s	remaining: 1m 43s
4000:	total: 5m 42s	remaining: 1m 25s
4200:	total: 5m 59s	remaining: 1m 8s
4400:	total: 6m 18s	remaining: 51.5s
4600:	total: 6m 33s	remaining: 34.2s
4800:	total: 6m 50s	remaining: 17s
4999:	total: 7m 5s	remaining: 0us

CatBoostClassifier(depth=6, eval_metric='AUC', iterations=5000, learning_rate=0.03, loss_function='Logloss', random_seed=42, verbose=200)

In [468]:
X_test = test_df_base.drop(columns=["uid"])

In [471]:
test_pred_cat = (final_cat.predict_proba(X_test))[:,1]

In [472]:
submission = pd.DataFrame({"uid": test_raw_df["uid"],"TARGET": test_pred_cat})

In [473]:
submission.to_csv("catboost_submission.csv",index=False)

In [475]:
submission["TARGET"].nunique()

39574